### ISSUE TITLE
Zusammenziehen von gleichen Namen aus verschiedenen Feldern

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#101]
Man betrachte folgendes MWE:

```
\documentclass[ngerman]{scrbook}
\usepackage{babel}
\usepackage{libertine}
\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
@Book{Amm,
  author        = {Ammianus <Marcellinus>},
  editor        = {Seyfarth, Wolfgang},
  title         = {Römische Geschichte},
  publisher     = WBG,
  location      = Munich,
  origlanguage  = {latin},
  translator    = {Seyfarth, Wolfgang},
  shorthand     = {Amm.},
  shortauthor   = {Ammian},
  keywords      = {ancient},
  options       = {ancient},
  commentator   = {Gerhard Wirth},
  date          = {1970/1974},
  introduction  = {Gerhard Wirth},
  sortshorthand = {Amm.},
}
@Book{Plin_nat,
  author       = {Plinius Secundus, Caius},
  editor       = {Roderich König and Gerhard Winkler},
  title        = {Naturkunde},
  publisher    = AWi,
  location     = {Düsseldorf},
  origlanguage = {latin},
  translator   = {Roderich König and Gerhard Winkler},
  shorthand    = {Plin. nat.},
  shortauthor  = {Plinius},
  keywords     = {ancient},
  options      = {ancient},
  date         = {1997/2007},
}
\end{filecontents*}
\usepackage{csquotes}
\usepackage[           
  backend=biber,
  style=archaeologie,
]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
  \nocite{*}
  \printbibliography
\end{document}
```

![bildschirmfoto 2016-09-22 um 12 35 30](https://cloud.githubusercontent.com/assets/12896078/18745058/1cfbfd7e-80c1-11e6-8f2c-78b57c0dd867.png)

Im zweiten Eintrag (`Plin_nat`) werden die Herausgeber und die Übersetzer zusammengezogen, im ersten Eintrag (`Amm`) hingegen wird `Gerhard Wirth` zweimal genannt: einmal als Kommentator, einmal als Einleitungsverfasser. 

Wie kann man es hinbekommen, dass ausgegeben wird. 
> mit einem Komm. und einer Einl. von Gerhard Wirth

, @moewew ? 
Mir ist leider nicht klar, wo dieses ›Zusammenziehen‹ der Namen im Code (`bbx`) stattfindet.

**Comment by moewew** [comment]
Sieh dir mal `editor+othersstrg`, `translator+othersstrg` bzw. deren `by...`-Versionen in `biblatex.def` an. Bedenke, dass es für alle zusammengezogenen Strings auch einen passenden Eintrag in der `.lbx` geben muss.

Soweit ich das sehe, gibt es zur Zeit keine Kombination, die weder `editor` noch `translator` drin hat. Dafür müsstest Du unter Umständen den Code der erwähnten Makros reproduzieren.
Du müsstest in `withothers` rumspielen.

**Comment by LukasCBossert** [comment]
Das wird echt komplex. Zumal dann ja nicht nur `withothers` geändert werden muss, sondern auch die manuell eingefügten `in...(translator)`, etc. 
Dann lieber die zweimalige Nennung oder man ›unterschlägt‹ eine Funktion (`commentator` oder `introduction`).

Solange eben eine Person `editor` oder `translator` ist, funktioniert es mit dem Rest auch prima.
