### ISSUE TITLE
\fullcite mit vollem Namen aller Autoren/Herausgeber, aber kein Eintrag in der Bibliographie

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#104]
Aus der `biblatex.def`:
```
\DeclareCiteCommand{\fullcite}
{\usebibmacro{prenote}}
{\usedriver
    {\DeclareNameAlias{sortname}{default}}
    {\thefield{entrytype}}}
{\multicitedelim}
{\usebibmacro{postnote}}
```
Wo muss das `\skipentry` hin, dass `\fullcite` nicht in der Bibliographie berücksichtigt wird?
Kann man ebenfalls einstellen, dass alle Namen der Autoren bzw. Herausgeber ausgegeben werden (wie in der Bibliographie)?

Oder geht das nur über ein `bibcheck`(http://tex.stackexchange.com/q/151994/98739), @moewew ? Danke!

**Comment by moewew** [comment]
`\skipentry` ist ein Befehl, der nicht in allen Situationen verfübar ist. Soweit ich weiß, kommt er nu in `bibchecks` und Ähnlichen zum Einsatz.

Bei `biblatex` gilt als Regel: alles was zitiert wurde, kommt in die Bibliographie. Das kann man dann mit `bibchecks`/`categories` verhindern. Du könntest z.B. alle zirtierten Einträge in die Kategorie `cited` aufnehmen, das bei `\fullcite` aber unterlassen.

Um alle Namen auszugeben, müsstest Du lokal `maxnames` und Freunde kapern und umbauen.

**Comment by LukasCBossert** [comment]
Hm, ok - ich sehe es ein: Das ist wohl dann doch ein zu individueller Wunsch. Ich werde es wohl dahingehend lösen, dass ich den Einträgen, die ich über `\fullcite` zitiere, ein `keyword` mitgebe, worüber dann in der Bibliographie der Eintrag ausgeschlossen wird.
Die Sache mit der Auflistung aller Namen wird darüber nicht gelöst sein, aber sei’s drum. 
Danke für die Einschätzung und schnelle Antwort.
