### ISSUE TITLE
Bei Option 'inreferences' label bleibt erhalten

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#111]
Folgendes MWE

```\documentclass{scrbook}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Book{Torelli_1995a,
  author    = {Torelli, Mario},
  editor    = {Fracchia, Helena and Gualtieri, Maurizio},
  title     = {Studies in the Romanization of Italy},
  publisher = {University of Alberta Press},
  location  = {Edmonton, Alberta},
  year      = {1995},
  groups    = {S659 Bantia},
  owner     = {Lukas C. Bossert},
  timestamp = {2014.05.21},
}
@Inreference{Torelli_1995,
  author         = {Torelli, Mario},
  title          = {Diribitorium},
  booktitle      = LTUR-short,
  pages          = {17\psq},
  year           = {1995},
  volume         = {2},
  bookpagination = {column},
  keywords       = {corpus},
  owner          = {Lukas C. Bossert},
  timestamp      = {2014.03.21},
}

@Incollection{Torelli_1995b,
  author       = {Torelli, Mario},
  title        = {The Creation of Roman Italy: The Contribution of Archaeology},
  pages        = {1--16},
  editor       = {Fracchia, Helena and Gualtieri, Maurizio},
  booktitle    = {Studies in the Romanization of Italy},
  publisher    = {University of Alberta Press},
  location     = {Edmonton, Alberta},
  year         = {1995},
  origlanguage = {italian},
  translator   = {Fracchia, Helena and Gualtieri, Maurizio},
}
\end{filecontents}
\usepackage[           
  backend=biber,
style=archaeologie,
 inreferences,
 lstabbrv,
 lstlocations,
 lstpublishers,
]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
	\footcite{Torelli_1995a}
	\footcite{Torelli_1995}
\footcite{Torelli_1995b}
\printbibliography
\end{document}
```
Ohne Option `inreferences`:

![bildschirmfoto 2017-07-18 um 23 20 31](https://user-images.githubusercontent.com/12896078/28340572-898b3910-6c10-11e7-88c0-7a121f86f1a9.png)
![bildschirmfoto 2017-07-18 um 23 20 22](https://user-images.githubusercontent.com/12896078/28340574-8bc59c5c-6c10-11e7-8771-54fd59c75f62.png)

Soweit alles in Ordnung.

Mit Option `inreferences` kommt raus:

![bildschirmfoto 2017-07-18 um 23 20 59](https://user-images.githubusercontent.com/12896078/28340543-735a8948-6c10-11e7-9114-42410e789aaa.png)
![bildschirmfoto 2017-07-18 um 23 20 53](https://user-images.githubusercontent.com/12896078/28340548-783f26d0-6c10-11e7-87be-8b379f8ed991.png)

Hier zeigt sich, dass intern `Torelli 1995a` beibehalten wird, obwohl dieser Eintrag nicht mehr in der Bibliographie auftaucht, sondern direkt als Vollzitat in der Fußnote ausgegeben wird.
In der Bibliographie soll natürlich stattdessen `1995a` und `1995b`stehen.

(M)eine Idee wäre bei
```
\newbibmacro*{cite:lexikon}{%
  \printfield{booktitle}%
  \setunit{\addspace}%
  \printfield{volume}%
  \setunit{\addspace}%
  \printfield[parens]{year}%
  \setunit{\addspace}%
  \iffieldundef{postnote}%
  {\printfield{pages}}%
  {\printfield{postnote}}%
  \usebibmacro{inreference:title+author}%
}
```
so etwas wie ein "clear label" o.ä. einzusetzen. Hast du mir einen Tipp, @moewew ? Vielen Dank!

**Comment by moewew** [comment]
Es würde nichts bringen, das `extrayear` später zu löschen. Du musst schon vorher verhindern, dass es zugewiesen wird. Denn dann würden die anderen beiden Quellen noch immer 'b' und 'c' anzeigen. Das so gelöschte 'a' trat ja sowieso nicht auf.

Es gibt die Option `skiplab`, die Du wahrscheinlich für `Torelli_1995` setzten willst, wenn `inreferences` aktiviert ist.

**Comment by moewew** [comment]
Ha! Ich habe vergessen, dass man `skiplab` auch per-type setzen kann
```
\ExecuteBibliographyOptions[inreference]{skiplab=true}
```
sollte es tun.

**Comment by LukasCBossert** [comment]
Genial! 
Mit 
```
\DeclareBibliographyOption{inreferences}[true]{\csuse{bool#1}{bbx:inreferences}
  \ExecuteBibliographyOptions[inreference]{skipbib=true}%
	\ExecuteBibliographyOptions[inreference]{skiplab=true}}
```
konnte ich es lösen. Vielen Dank, @moewew !!
