### ISSUE TITLE
Änderung in biblatex 3.8: origlanguage wird eine Liste

### ISSUE THREAD

**Issue by moewew** [LukasCBossert/biblatex-archaeologie#113]
In der nächsten Version von `biblatex` wird `origlanguage` eine `list` werden und kein `field` mehr sein.

Die Zeile
https://github.com/LukasCBossert/biblatex-archaeologie/blob/78e38bde4d6261f38b574ced2aeaa7f6519873b0/archaeologie.bbx#L202
müsste dann entsprechend angepasst werden.

Für den Hintergrund siehe https://github.com/plk/biblatex/issues/594

Vielleicht sind auch die weiteren Änderungen in Version 3.8 interessant https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org

**Comment by LukasCBossert** [comment]
super! Danke für den Hinweis. Ich werde es im Auge behalten!

**Comment by LukasCBossert** [comment]
Wie ich sehe, wird sich auch

https://github.com/LukasCBossert/biblatex-archaeologie/blob/aad2485c807c5099f584426662c9124e369da428/archaeologie.bbx#L229-L233

ändern, wobei mir nicht klar ist, ob es dann nur noch 

```
\DeclareLanguageMappingSuffix{archaeologie-}
```
heißt oder ob die Dateien in `german-archaeologie` etc. umbenannten werden müssen, damit sie mit 

```
\DeclareLanguageMappingSuffix{-archaeologie}
```
gefunden werden. Und was ist mit einer Sprache, die nicht mit dem Stil `archaeologie` mitkommt?

**Comment by moewew** [comment]
Da es um Suffixe geht, kannst Du mittels
```
\DeclareLanguageMappingSuffix{-archaeologie}
```
dann automatisch Dateien der Art `english-archaeologie.lbx` laden.

In der Tat bekommt man aber Fehler für nicht unterstütze Sprachen, ich habe das mal gemeldet https://github.com/plk/biblatex/issues/612. Das sollte nicht der Fall sein denke ich, es sollte wohl die Standardlokalisierung geladen und eine Warnung ausgegeben werden. Ich habe das noch nicht vollständg verstanden.

**Comment by LukasCBossert** [comment]
Ok, aber dafür müsste ich dann für `biblatex 3.8` die `.lbx`-Dateien von `archaeologie` umbenennen. Für den Nutzer wird es keine Rolle spielen.

**Comment by moewew** [comment]
Wir nähern uns langsam der Veröffentlichung von Version 3.8. Wann genau es so weit ist, kann ich nicht sagen, aber PLK peilt einen Termin in sehr naher Zukunft an (dieses Wochenende, nächste Woche), siehe https://github.com/plk/biber/issues/164.

Die weiteren Änderungen können https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org und https://github.com/plk/biblatex/wiki entnommen werden.

**Comment by LukasCBossert** [comment]
Vielen Dank für das Update. Wenn ich die Anpassung gemacht habe, werde ich dich nochmals um einen "check" bitten, ob das alles stimmt.

**Comment by moewew** [comment]
Es haben sich weitere Änderungen ergeben.

So heißt `extrayear` jetzt `extradate` und `\DeclareSortingScheme` `\DeclareSortingTemplate`. Die alten Namen sollten noch immer funktionieren. Aber es wäre wünschenswert, wenn die neuen Befehle genutzt würden.

Alle Änderungen sind in https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org und https://github.com/plk/biblatex/wiki aufgelistet. Vielleicht findest Du ja noch neue Funktionen, die Du gebrauchen kannst.

**Comment by LukasCBossert** [comment]
Irgendwas stimmt da nicht? 
In der Log bekomme ich

> ./arch-multivolume.tex:65: Undefined control sequence.
\blx@theformat #1->\iflistequalstr 
                                   {origlanguage}{greek}{#1}{\mkbibemph {#1}}

in der `bbx` steht: `\DeclareFieldFormat{origtitle}{\iflistequalstr{origlanguage}{greek}{#1}{\mkbibemph{#1}}}` 
?

**Comment by moewew** [comment]
Den Befehl `\iflistequalstr` gibt es nicht. Bei Feldern ist es sinnvoll zu fragen, ob sie mit einem String übereinstimmen. Aber Listen können mehrere Elemente beinhalten, daher kann hier nicht gefragt werden, ob eine Liste gleich einem String ist.

**Comment by LukasCBossert** [comment]
Oh, na klar. Darüber habe ich nicht nachgedacht. 

Dann lässt sich die Abfrage, ob `origlanguage` bspw. `greek` ist, gar nicht mehr machen?

**Comment by moewew** [comment]
Leider sind die `biblatex` Listenfelder nicht mit den Listen aus `etoolbox` kompatibel. Daher kann man die dortigen Makros nicht verwenden. Ich würde nicht versuchen, `origlanguage` abzufragen, sondern stattdessen eine Option definieren. Das ist etwas mehr Arbeit für den Nutzer, aber auch weniger fehleranfällig.

**Comment by LukasCBossert** [comment]
Die Sache mit der `origlanguage` war nicht so tragisch. Von einer Option würde ich momentan abraten, da die Nutzer dann gleich den Titel kursiv setzen können, erfordert gleich viel Aufwand wie eine Option zu setzen.

Ansonsten: Update ist raus. 
Vielen Dank für die Hilfe!

**Comment by moewew** [comment]
Wenn Du in den nächsten Tagen ein bisschen Zeit hast, wäre es klasse, wenn Du die Entwicklungsversion von `biblatex` 3.11 (entweder von GitHub https://github.com/plk/biblatex oder von SourceForge https://sourceforge.net/projects/biblatex/files/development/) testen könntest. Der Code, der die `.lbx`-Dateien lädt, musste überarbeitet werden, und wir möchten sicherstellen, dass wir keine bösen Bugs eingebaut haben. Alle anderen Änderungen finden sich unter https://github.com/plk/biblatex/wiki. Da Dein Stil ja auch eigene `.lbx`-Dateien nutzt, eignet er sich gut zum Testen. Vielleicht kannst Du Dir ja mal ansehen, ob auch mit 3.11 alles noch so aussieht wie es soll.

**Comment by LukasCBossert** [comment]
Mache ich gerne. Habe bisher noch nicht mit einer `biblatex`-dev Version gearbeitet. Ist aber sicherlich machbar!? Muss `biber` auch in der `dev`-Version heruntergeladen werden, damit `biblatex`3.11 läuft?

**Comment by moewew** [comment]
Vielen Dank.

Oft ist auch die passende Biber-Version nötig, hier solltest Du aber mit 3.10 hinkommen, da sich bei Biber nicht so viel geändert hat.

Wenn Du `biblatex` nicht in einen lokalen TeX-Tree legen kannst/willst, dann ist es am einfachsten, einfach alle Dateien aus `tex/latex/biblatex` in denselben Ordner zu packen, damit das gut funktioniert, müssen aber auch die Inhalte der `bbx`-, `cbx`-, `lbx`-Ordner eine Ebene nach oben auf dasselbe Level wie die `.sty`-Datei verschoben werden.

**Comment by moewew** [comment]
Falls alle Stricke reißen und bevor Du Dir Deine Installation zerschießt, sollte es für die relevanten Tests genug sein, die `.sty`-Datei von https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/biblatex.sty heruntertzuladen und in einen Test-Ordner zu legen, in dem Du nachher die `.tex`-Dateien auch hast. Dann musst Du nur die `biblatex.sty` öffnen und in den Zeilen 15 und 16 vernünftige Werte angeben, z.B. statt der Platzhalter `DATE` und `VERSION`

```
\def\abx@date{2018/02/06}
\def\abx@version{3.11}
```

**Comment by LukasCBossert** [comment]
So habe ich es nun gemacht und die `biblatex.sty` heruntergeladen und mit `archaeologie.tex` ausprobiert. Hat alles geklappt – das PDF und die Angaben sind so, wie sie sein sollen bzw. wie sie auch mit `biblatex 3.10` waren (oder hätte sich etwas ändern sollen?).

**Comment by moewew** [comment]
Vielen Dank fürs Testen. Die Ausgabe sollte so sein wie mit Version 3.10. Es gibt ein, zwei Änderungen, die auch die Ausgabe beeinflussen sollten, aber davon muss Dein Stil nicht betroffen sein. Ansonsten wollten wir gerade nicht, dass sich etwas ändert.
