### ISSUE TITLE
Klammern in textcite

### ISSUE THREAD

**Issue by moewew** [LukasCBossert/biblatex-archaeologie#116]
Man betrachte
```
\documentclass[english,ngerman]{scrbook}
\usepackage{filecontents,babel}
\usepackage[           
backend=biber,
style=archaeologie,
]{biblatex} 

\addbibresource{biblatex-examples.bib}

\begin{document}
\textcite{knuth:ct:a,knuth:ct:b,knuth:ct:b}
\end{document}
```
Bei mir gibt das Beispiel einen Fehler wegen `cbx:parens`
https://github.com/LukasCBossert/biblatex-archaeologie/blob/96f9b3385a7b82e19d5bc26c655bb8a5f5464ca4/archaeologie.cbx#L431
Außerdem sind verständlichrweise die Klammern inkorrekt.

**Comment by moewew** [comment]
Es scheint mir, als würde es schon helfen, in der problematischen Zeile `cbx:parens` durch `cbx:yearinparens` zu ersetzen.

**Comment by LukasCBossert** [comment]
Du hast absolut recht, `cbx:parens` macht da auch keinen Sinn, weil weiter oben (https://github.com/LukasCBossert/biblatex-archaeologie/blob/96f9b3385a7b82e19d5bc26c655bb8a5f5464ca4/archaeologie.cbx#L417) auch schon `cbx:yearinparens` abgefragt wird.
Danke für den Hinweis! Ich nutze `textcite{x,y,z}` nie, daher fiel es mir beim Testen nicht auf.
Es wird Zeit eine eigene, richtige, Test-Suite für `archaeologie` aufzusetzen.
