### ISSUE TITLE
test smartcite

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#119]

**Comment by LukasCBossert** [comment]
Folgendes MWE 

```
\documentclass[ngerman]{scrbook}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[utf8]{inputenc}
  \usepackage[T1]{fontenc}
  \usepackage{lmodern}
\else
  \ifXeTeX
  \usepackage{fontspec}
		\def\compiler{\hologo{XeLaTeX}}
  \else 
	  \usepackage{fontspec}
  \usepackage{luatextra}
  \usepackage{luaotfload}
	\def\compiler{\hologo{LuaLaTeX}}
\fi
  \defaultfontfeatures{Ligatures=TeX}
\fi
\listfiles
\usepackage{libertine}
\defaultfontfeatures[AnonymousPro]
  {
  Extension  = .ttf  ,
  BoldFont  = AnonymousPro-Bold  ,
  ItalicFont  = AnonymousPro-BoldItalic  ,
  BoldItalicFont = AnonymousPro-Italic  ,
  UprightFont  = AnonymousPro-Regular  ,
  }
\setmonofont[Scale= MatchUppercase]{AnonymousPro}
\setmainfont[Numbers = {Monospaced, OldStyle}]{Libertinus Serif}
\setsansfont{Libertinus Sans}
\usepackage{babel}
\usepackage{xcolor}
\definecolor{codeblue}{RGB}{0,65,137}
\definecolor{codegreen}{RGB}{147,193,26}
\definecolor{codegray}{rgb}{0.5,0.5,0.5}
\definecolor{codepurple}{rgb}{0.58,0,0.82}
\definecolor{backcolour}{rgb}{0.95,0.95,0.92}
\usepackage[  
  backend=biber,
%style=../biblatex-archaeologie/archaeologie,
style=archaeologie,
  inreferences,
	lstabbrv,
	lstlocations,
	lstpublishers,autocite=inline,
]{biblatex}	
\addbibresource{archaeologie-examples.bib}
\usepackage[%
  skins,%
  listings,%
  breakable,%
]{tcolorbox}
\lstMakeShortInline{|}


\tcbset{examplebox/.style={%
  boxrule=0pt,
  bottomrule=2pt,
  toprule=2pt,
  colframe=codeblue,
  colback=codegreen!10,
  coltitle=codegreen!10,%  coltitle=codeblue,
  bicolor,
  sharp corners,
  fontupper=\small\ttfamily,
  colbacklower=codeblue!10,
  fonttitle=\sffamily\bfseries,
}}


\newtcblisting{example}{%
  before skip=\baselineskip,
  examplebox,
  breakable,
  %  sidebyside,
  listing and text,
}

	
\begin{document}

\begin{example}
Public space is part of a city.\smartcite{Osland2016} 
And sometimes more than that.\footnote{\smartcite[cf.][]{Evangelidis2014}.}
\end{example}
Public space is part of a city.\smartcite{Osland2016} 
And sometimes more than that.\footnote{\smartcite[cf.][]{Evangelidis2014}.}\par

\begin{example}
Public space is part of a city.\smartcites{Osland2016}{Evangelidis2014} 
And sometimes more than that.\footnote{\smartcites{Osland2016}[cf.][]{Evangelidis2014}.}
\end{example}
Public space is part of a city.\smartcites{Osland2016}{Evangelidis2014} 
And sometimes more than that.\footnote{\smartcites{Osland2016}[cf.][]{Evangelidis2014}.}
\end{document}
  ```

führt zu 

![bildschirmfoto 2017-08-28 um 17 15 04](https://user-images.githubusercontent.com/12896078/29779969-7818d4d4-8c14-11e7-8525-ec7ca5396496.png)

> `\smartcite` funktioniert an sich, nicht jedoch innerhalb einer `listings`-Umgebung

**Comment by LukasCBossert** [comment]
@moewew Hast du hierzu eine Idee, warum `\smartcite` nicht korrekt funktioniert?

**Comment by moewew** [comment]
Das sollte daran liegen, dass die Fußnotenerkennung in `example` nicht funktioniert. `biblatex` muss den Befehl `\footnote` patchen, damit es Fußnoten erkennt. Ich gehe davon aus, dass `example` eine lokale Definition hat, an die `biblatex` nicht herankommt (der `\footnote`-Befehl wird ganz zu Beginn des Dokuments angepasst).

**Comment by moewew** [comment]
```
\makeatletter
\patchcmd{\@mpfootnotetext}%
  {\color@begingroup}
  {\color@begingroup\toggletrue{blx@footnote}}
  {}
  {}
\makeatother
```

**Comment by moewew** [comment]
Ich hab mal einen Patch für `biblatex` losgeschickt. https://github.com/plk/biblatex/commit/1d2172c4147abf402532e9d07a6f70c26a6b6981

**Comment by LukasCBossert** [comment]
Aha, dann war es gar nicht so einfach und ich wäre nie darauf gekommen. Danke!

**Comment by LukasCBossert** [comment]
@moewew Der Patch funktioniert beim obigen MWE, nicht aber bei der Dokumentation (ltxdoc) von `archaeologie.tex` ?!

**Comment by moewew** [comment]
Kannst Du das erstmal gegen die neue dev-Version von `biblatex` testen (sie ist leider nicht auf sourceforge, also musst du sie von GitHub holen, eine neue Version von Biber ist nicht nötog)? Ansonsten würde mir ein Minimalbeispiel (und nicht die ganze Doku, da weiß ich nicht, wo ich anfangen muss, zu suchen) weiterhelfen.

**Comment by moewew** [comment]
Soweit ich das sehe, lädt die Doku `hyperref`. In dem Fall ist mein Patch von oben in der Tat nicht ausreichend. https://github.com/plk/biblatex/commit/1d2172c4147abf402532e9d07a6f70c26a6b6981 allerdings patcht auch `\H@@mpfootnotetext`, wenn `\@mpfootnotetext` nicht gepatcht werden kann. Das sollte dafür sorgen, dass das auch mit `hyperref` funktioniert. Wenn Du es testen könntest, wäre das natürlich trotzdem super. Ich denke aber, dass es gehen müsste und habe es im Kleinen schon ausprobiert.

**Comment by LukasCBossert** [comment]
scheint wohl behoben zu sein.
