### ISSUE TITLE
Umbenennung von  "number"  in "part" bei "journal"

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#120]
Für einheitliche Handhabe: `number` als fortführende Zahlenfolge (vgl. `series` & `number`) ist bei `journal` etwas widersprüchlich; besser wäre `part` zu benutzen, da es sich um eine (idR) jährlich wiederholende Nummerierung handelt.

Dank an @charlott3 für den Hinweis

**Comment by moewew** [comment]
Möglicherweise habe ich falsch verstanden, was hier geplant ist, aber ich weiß nicht, ob das so eine gute Idee wäre. Die Standard-Einteilung in `volume` (durchgehend) und `number` (als Teil eines `volume`s) bei `@article` führt zwar bei einigen Nutzern zu Verwirrung (besonders wegen `number` statt `issue`, das es bei `biblatex` auch gibt, aber selten passt), ist aber überall offiziell verbrieft und erklärt. Ein Sonderweg von `biblatex-archaeologie` - zumal mit einem unbekannten Feld wie `part` - wäre meiner Meinung nach eindeutig kontraproduktiv.

Man beachte auch die Amerkungen der `biblatex`-Dokumentation dazu (Hervorhebung meine)
> `number` [...] The number of a journal or the volume/number of a book in a `series `.

> `part` [...] The number of a partial `volume`. *This field applies to books only, not to journals.*

Ich denke, der `biblatex`-Entwickler war sich der etwas unglücklichen Benennung mit Bedeutungsüberschneidungen zwischen verschiedenen Typen sehr wohl bewusst, aber die Erhaltung von Abwärtskompatibilität mit `.bst`-Stilen wird ihn dazu gebracht haben, das hinten anzustellen.

**Comment by LukasCBossert** [comment]
Vielen Dank für deine Einschätzung. Du hast vollkommen recht, es wäre kontraproduktiv hier einen Sonderweg zu gehen. Zumal es an sich bereits fest etabliert ist `part` für Bücher zu nehmen. 
Wir lassen also alles beim Alten.
