### ISSUE TITLE
Collaborator!?

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#125]
@moewew Für deine viele tolle Hilfestellungen würde ich dich gerne als offizieller Collaborator/Ko-Auor aufnehmen - Einladung ist verschickt.

**Comment by moewew** [comment]
Vielen Dank für die Ehre. Mit dieser Bezeichnung kommt aber meiner Meinung nach eine gewisse (moralische) Verpflichtung, der ich gerne entgehen würde. Das heißt aber natürlich nicht, dass ich nicht daran Freude hätte oder nicht gewillt wäre, bei kniffligen Problemen oder interessanten Fragen mitzuarbeiten.

**Comment by LukasCBossert** [comment]
Es gäbe keinerlei (moralische) Verpflichtung, es ist nur eine Möglichkeit für deine Hilfe "Danke" zu sagen und deine Code-Arbeit zu honorieren (bisher profitiere ich nur von dir ohne mich revanchieren zu können). Das Angebot steht jederzeit.
