### ISSUE TITLE
Silbentrennung in der Sprache des Eintrags, Strings in der Hauptsprache des Dokuments

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#129]
`langid` stellt auch die `bibstrings` um, was nicht gewünscht ist. Es sollen nur die Regeln für die Silbentrennung geladen werden, `bibstrings` davon ausgenommen.

**Comment by moewew** [comment]
Das wird von `autolang` kontrolliert.

Mit `autolang=other` werden Einträge in einer zur Sprache passenden `otherlanguage`-Umgebung gesetzt, diese ändert auch die bibstrings.

Mit `autolang=hyphen` wird `hyphenrules` genutzt, das ändert nur die Silbentrennung und mehr nicht.

**Comment by LukasCBossert** [comment]
Ok, dann ist `autolang=hyphen` was ich gesucht habe und was für `archaeologie` sinnvoll ist.

**Comment by LukasCBossert** [comment]
@moewew Das funktioniert auch an sich, aber es werden auch die Interpunktionsregeln geladen, wie bspw. bei Französisch das doppelte Leerzeichen bei doppeltem Satzzeichen. Lässt sich das auch ausschalten?

**Comment by moewew** [comment]
Das weiß ich nicht. Soweit ich weiß ist `hyphenrules` schon deer Befehl, der am wenigsten umstellt. Eigentlich sollten das nur die Trennmuster sein, aber vielleicht gehören die Interpunktionsregeln so fest zum Trennmuster, dass man sie nicht trennen kann. Ein Beispiel zum Rumspielen könnte helfen, aber ich hab nicht so viel Ahnung von `babel` und `polyglossia`.
