### ISSUE TITLE
kein Komma vor `in` bei fehlendem Titel

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#131]
```
@Incollection{Koudounaris1985,
  author       = {Koudounaris, Aristides L.},
  booktitle    = {Antike Kunst auf Zypern im Museum der Pierides Stiftung},
  year         = {1985},
  booksubtitle = {L’Art Chypriote antique au Musée de la Fondation Piéridès},
  publisher    = {Pierides Stiftung},
  pages        = {19--21},
  editor       = {Karageorghis, Vassos},
  location     = {Larnaka},
  groups       = {21rogge},
}
```

**Comment by moewew** [comment]
Das ist in

https://github.com/LukasCBossert/biblatex-archaeologie/blob/a77f6a0b68090fee5f95a8d0241cc36d8456009b/archaeologie.bbx#L1142-L1145

so festgelegt.

**Comment by LukasCBossert** [comment]
genau, aber dennoch wird komischerweise ein Komma ausgegeben. 

```
\documentclass[german,ngerman]{scrbook}
\usepackage{filecontents,babel}
\begin{filecontents}{\jobname.bib}
@Inbook{Kohlmeyer1983,
  author       = {K. Kohlmeyer},
  booktitle    = {Tierbilder aus vier Jahrtausenden},
  year         = {1983},
  editor       = {U. Gehrig},
  booksubtitle = {Antiken der Sammlung Mildenberg},
  pages        = {20 Nr. 9},
  location     = Mainz,
}
\end{filecontents}
\usepackage[           
  backend=biber,
%style=../biblatex-archaeologie/archaeologie,
  style=archaeologie,
]{biblatex}	
\addbibresource{\jobname.bib}

\begin{document}
\printbibliography
\nocite{*}
\end{document}
  ```

**Comment by moewew** [comment]
Ach so, ich wusste nicht, was das gewünschte Ergebnis war.

Das Problem ist das `\setunit{\isdot\addcomma\addspace}` in

https://github.com/LukasCBossert/biblatex-archaeologie/blob/3b56d5a277ddc383356aac29aaa5a1266c3b5cd9/archaeologie.bbx#L502-L504

das sorgt immer für ein Komma vor dem 'in'. Ich hätte erwartet, dass die Standarddefinition 
```
\newbibmacro*{in:}{%
  \printtext{%
    \bibstring{in}\intitlepunct}}
```
ausreicht. Aber ich weiß nicht für welche Fälle das `\setunit{\isdot\addcomma\addspace}` eingebaut wurde.

**Comment by LukasCBossert** [comment]
Mit `\setunit{\isdot\addcomma\addspace}` habe ich den nachfolgenden Fall lösen können, bei bei einem Titel oder was auch immer davor mit einem `.` endet,  dennoch ein Komma vor dem `in:` gesetzt wird und das `in:` nicht großgeschrieben wird, weil ja zuvor ein Punkt steht.

```
\documentclass[german,ngerman]{scrbook}
\usepackage{filecontents,babel}
\begin{filecontents}{\jobname.bib}
@incollection{EckTauschungOffentlichkeitProzess1997,
  langid = {german},
  location = {{München}},
  title = {Die Täuschung der Öffentlichkeit. Der Prozess gegen Cnaeus Calpurnius Piso im Jahre 20 n.\,Chr.},
  isbn = {978-3-406-42686-5},
  booktitle = {Große Prozesse der römischen Antike},
  publisher = {{Beck}},
  author = {Eck, Werner},
  editor = {Manthe, Ulrich},
  date = {1997},
  pages = {128--145},
  keywords = {(DE-588)4076778-4,Imperium Romanum,Italien Geschichte 753 v Chr-500,Kongress,Reich Rom,Römisches Reich,Römisches Reich Antike,Prozess,Geschichte 200 v Chr-300,Augst 1996,Gerichtsverfahren,(DE-588)4047577-3,Gerichtsprozess,Prozesse}
}
\end{filecontents}
\usepackage[           
  backend=biber,
%style=../biblatex-archaeologie/archaeologie,
  style=archaeologie,
]{biblatex}	
\addbibresource{\jobname.bib}

\begin{document}
\printbibliography
\nocite{*}
\end{document}
  
```

**Comment by moewew** [comment]
Da sehe ich zwei Möglichkeiten.

Entweder müssen Nutzer Punkte am Ende von `title`-Feldern selbst mit `\isdot` bearbeiten, wenn sie Abkürzungen anzeigen und nicht den Satz beenden.
Oder Du machst das mit
```
\DeclareFieldFormat*{title}{#1\isdot}
```
selbst.

**Comment by moewew** [comment]
Wenn Du damit zur Standard-Definition von `in:` zurückgehen kannst, hätte das den Vorteil, dass Du damit sofort ein von mir erzeugtes Problem löst.
Ich habe in

https://github.com/LukasCBossert/biblatex-archaeologie/blob/3b56d5a277ddc383356aac29aaa5a1266c3b5cd9/archaeologie.bbx#L502-L504

eine schließende Klammer zu viel gelassen.

**Comment by LukasCBossert** [comment]
Hiermit klappt beides, `\isdot` ist drin und bei fehlendem Titel kein Komma:

```
\renewbibmacro{in:}{%
 \setunit{\isdot%
   \iffieldundef{title}
     {}
     {\addcomma}%
     \addspace}%
     \printtext{\bibstring{in}\intitlepunct}}
```
Spricht da etwas dagegen?

**Comment by moewew** [comment]
Das ist nicht ganz mein Geschmack. Ich finde es immer unschön ein Makro mit Befehlen für Zeichensetzung zu beginnen.

Mein Vorschlag wäre
```
\DeclareFieldFormat*{title}{#1\isdot}
```
und die Standard-Definition von `in:`.

**Comment by moewew** [comment]
Technisch gesehen spricht aber glaube ich nichts gegen Deinen Vorschlag. Ich bin mir aber nicht ganz sicher.

**Comment by LukasCBossert** [comment]
Aber mit deinem Vorschlag klappt es auch und man muss die Standard-Definition von `in:` nicht anfassen, was immer besser ist (ich meine, dass "früher" auch per default ein `in:` bei Zeitschriften gesetzt wurde, weswegen ich es geändert hatte). 

Ich teste gerade noch, ob 
```
\DeclareFieldFormat*{subtitle}{#1\isdot}
```
auch notwendig ist

**Comment by moewew** [comment]
Bin mir ziemlich sicher, dass `\DeclareFieldFormat*{subtitle}{#1\isdot}` nicht nötig ist.
Normalerweise werden Titel mit
```
\printtext[title]{%
  \printfield[titlecase]{title}%
  \setunit{\subtitlepunct}%
  \printfield[titlecase]{subtitle}}
```
ausgegeben. Da wird das Format `subtitle` gar nicht benutzt.

**Comment by LukasCBossert** [comment]
Selbstverständlich hast du recht (sonst hättest du das sicherlich auch vorgeschlagen wenn das bei `subtitle` notwendig wäre). Alle Tests sind bestanden.
