### ISSUE TITLE
@Strings mit biblatex 3.9/biber 2.9 nicht mehr erkannt.

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#137]
Mit dem Versionswechsel werden die definierten Makros (archaeologie-lstlocations, archaeologie-lstabbrv etc.) nicht mehr erkannt!?

**Comment by moewew** [comment]
https://github.com/plk/biber/issues/204

**Comment by LukasCBossert** [comment]
ah, vielen Dank. In die issues von `biber` hatte ich natürlich nicht geschaut. Dann warte ich auf das nächste update.
