### ISSUE TITLE
Anzeige AutorInnennamen im Fließtext

### ISSUE THREAD

**Issue by a2n1ka** [LukasCBossert/biblatex-archaeologie#138]
Gibt es eine Möglichkeit, bei der ersten Nennung eines Namens den Vornamen abgekürzt und den Nachnamen ausgeschrieben darzustellen, während bei allen folgenden Nennungen NUR noch der Nachname steht? Und lässt sich das auch pro Kapitel steuern?

**Comment by LukasCBossert** [comment]
Habe ich eingebaut. Soweit ich sehe, läuft es recht analog zu `name:fancy`, @moewew : https://github.com/LukasCBossert/biblatex-archaeologie/commit/be2a19649d4d3a933ed46d90c689a0d4092d80d2

Falls es keine Code-Einwände gibt, wird dieses Feature mit `citeauthorformat=firstfullthenfamily` in Version 3.5.6 demnächst veröffentlicht.

Bzgl. der Steuerung der vollen Namensanzeige pro Kapitel bin ich noch am Überlegen, ob das mit 

```
\usepackage{xpatch}
\xpretocmd{\chapter}{\citereset}{}{}
```
elegant (genug) ist oder ob das einen zu großen Eingriff in das Dokument ist. Was meinst du, @moewew ?


@a2n1ka : Du kannst 
```
\usepackage{xpatch}
\xpretocmd{\chapter}{\citereset}{}{}
```
in deiner Präambel laden und den ›Reset‹ erstmals selbst steuern. Pro Kapitel oder auch pro Section
```
\usepackage{xpatch}
\xpretocmd{\section}{\citereset}{}{}
```

**Comment by moewew** [comment]
Den Code für `citeauthor:firstfullthenfamily` könnte man jetzt schon eindampfen, da tun einige Abfragen nicht mehr so viel. Die Frage ist aber, was genau das Format tun soll? Wie soll es mit `uniquename` interagieren.

Meiner Meinung nach sollte es wie folgt sein:

- Wenn der ganze Name für `uniquename` nötig ist, wird immer der ganze Name angezeigt.
- Wenn Initialen nötig sind, gibt es immer Initialen.
- Wenn der Familienname reicht, gibt es beim ersten Mal Initialen, danach nur noch den Familiennamen.

Dafür wäre
```latex
\DeclareNameFormat{labelname}{%
  \cbx@ifnameseen{\thefield{hash}}
    {}
    {\ifnumequal{\value{uniquename}}{0}
       {\stepcounter{uniquename}}
       {}%
     \cbx@nametracker{\thefield{hash}}}%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
    \usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:andothers}}
```
gut.

Statt `\xpretocmd{\chapter}{\citereset}{}{}` gibt es bereits die Option `citereset` mit den möglichen Werten `none`, `part`, `chapter`, `section`, `subsection`, die genau das schon tut.

**Comment by LukasCBossert** [comment]
Ich stimme dir zu @moewew , wobei
> Wenn der Familienname reicht, gibt es beim ersten Mal Initialen, danach nur noch den Familiennamen.

dies dann nicht einem ›firstfull‹ entsprechen würde?

Ja, `citeauthor:fancy` war damals eine Notlösung, weil eine andere (stringentere) Benennung bei mir nicht funktionieren wollte. 

Ich kann dein Code aber nicht kompilieren.

```
\documentclass[german,ngerman,parskip=full]{scrartcl}
\usepackage{filecontents,babel}

\begin{filecontents}{\jobname.bib}
@Book{Cic:Att,
  author       = {Tullius Cicero, Marcus},
  editor       = {Kasten, Helmut},
}

@Inproceedings{HansMeier,
  author       = {Hans Meier},
}
@Inproceedings{aa,
author = {Anton Berger and Toni Meier}}

\end{filecontents}
\usepackage[           
  backend=biber,
style=../biblatex-archaeologie/archaeologie,
citeauthorformat=firstfullthenfamily,
]{biblatex}	
\addbibresource{\jobname.bib}

\DeclareNameFormat{citeauthor:firstfullthenfamily}{%
  \cbx@ifnameseen{\thefield{hash}}
    {}
    {\ifnumequal{\value{uniquename}}{0}
       {\stepcounter{uniquename}}
       {}%
     \cbx@nametracker{\thefield{hash}}}%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
    \usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:andothers}}

\begin{document}
  \citeauthor{HansMeier}\par
  \citeauthor{HansMeier}\par
  \citeauthor{HansMeier}\par
\citeauthor{Cic:Att}\par
\citeauthor{Cic:Att}\par
\citeauthor{aa}\par
\citeauthor{aa}\par

\section{ neu}
 \citeauthor{HansMeier}\par
  \citeauthor{HansMeier}\par
\citeauthor{Cic:Att}  \par
\citeauthor{Cic:Att}  \par
  \citeauthor{aa}\par
  \citeauthor{aa}\par
\printbibliography  
\nocite{*}
\end{document}
  

```

**Comment by LukasCBossert** [comment]
Halt, ich nehm es zurück... Das `@` war schuld. funktioniert natürlich, wenn ich den gleich in die `.cbx` packe.

**Comment by LukasCBossert** [comment]
jetzt fehlt nur noch, dass die erstnennung den vollen Namen ausgibt @moewew

**Comment by moewew** [comment]
Sorry, das `citeauthor:firstfullthenfamily` von hier war natürlich das ursprünglich angefrage `citeauthor:firstinitialsthenfamily`. Der Code sollte eigentlich genau wie beschrieben funktionieren, nur meine Benennung war Mist. Soll es jetzt doch anders sein? Von vollem Namen bei Erstnennung war doch nicht die Rede?

**Comment by LukasCBossert** [comment]
Bisher gab es die Option `firstfull`, die zuerst den vollen Namen und dann bei der Zweitnennung Initial und Nachname hatte.

Die oben angefragte Idee war, zuerst voller Name und dann nur Nachname.

Aber warum dann nicht auch gleich noch die dritte Option ermöglichen: zuerst Vornameninitial und bei Zweitnennung Nachname?!

Die "neue" Option hast du hiermit umgesetzt, oder?!

```
\DeclareNameFormat{citeauthor:firstinitialsthenfamily}{%
  \cbx@ifnameseen{\thefield{hash}}
    {}
    {\ifnumequal{\value{uniquename}}{0}
       {\stepcounter{uniquename}}
       {}%
     \cbx@nametracker{\thefield{hash}}}%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
    \usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:andothers}}
```

**Comment by moewew** [comment]
Huch, jetzt bin ich verwirrt. Ich dachte es sei oben angefragt gewesen: zuerst Initialen, dann nur Nachname. Das tut mein Code (mit den nötigen Ausnahmen für `uniquename`). Außerdem hatten wir schon erst voll, dann Initialen.

Natürlich kannst Du auch erst voll, dann nur Familie haben (mit den passenden Ausnahmen für Initialen).
Das wäre dann
```latex
\DeclareNameFormat{citeauthor:firstfullthenfamily}{%
  \cbx@ifnameseen{\thefield{hash}}
    {\ifcase\value{uniquename}%
       \usebibmacro{name:family}
         {\namepartfamily}
         {\namepartgiven}
         {\namepartprefix}
         {\namepartsuffix}%
     \or
       \ifuseprefix
         {\usebibmacro{name:given-family}   
           {\namepartfamily}
           {\namepartgiveni}
           {\namepartprefix}
           {\namepartsuffixi}}
         {\usebibmacro{name:given-family}
           {\namepartfamily}
           {\namepartgiveni}
           {\namepartprefixi}
           {\namepartsuffixi}}%
     \or
       \usebibmacro{name:given-family}
         {\namepartfamily}
         {\namepartgiven}
         {\namepartprefix}
         {\namepartsuffix}%
     \fi}
    {\usebibmacro{name:given-family}
       {\namepartfamily}
       {\namepartgiven}
       {\namepartprefix}
       {\namepartsuffix}
     \cbx@nametracker{\thefield{hash}}}%
  \usebibmacro{name:andothers}}
```
Da sich jetzt hier einiges an Code doppelt, könnte man darüber nachdenken, da etwas auszulagern. Da müsste man mal sehen, ob das ohne Scherben geht.

**Comment by LukasCBossert** [comment]
Du hast recht, _ich_ habe die Frage von @a2n1ka falsch verstanden. Wie auch immer, jetzt haben wir drei Möglichkeiten und schadet ja nicht. Auslagern ist ja immer schick, aber ich bin immer schon froh, wenn alles funktioniert. 

Hast du bei #139 gesehen, `citereset=section` ist da ohne Funktion. Du hast da auch was gepatcht, kann das daran liegen?

**Comment by LukasCBossert** [comment]
@a2n1ka Deine Frage hat zu zwei neuen Namensformatiermöglichkeiten geführt, die demnächst auf CTAN hochgeladen werden.

**Comment by LukasCBossert** [comment]
zur Info. Version 3.5.6. ist auf CTAN hochgeladen und wohl ab morgen verfügbar. Danke nochmals an @moewew

**Comment by a2n1ka** [comment]
Fantastisch! Danke euch für eure Arbeit!
