### ISSUE TITLE
Option initials abhängig von biber-version

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#143]
Vgl. #57: Da ab `biber 2.11` diese Option nicht mehr funktionieren wird, wäre es sicherlich hilfreich, wenn man einen Schalter definieren kann, der die `biber`-version prüft. 
Dann kann man für alle Versionen vor `2.11` die Option zulassen und für alle späteren sie ausschalten und mit einer Warnung versehen.

Nur, wie kann ich die version von `biber` aus LaTeX heraus abfragen, um sie zu vergleichen @moewew ?

**Comment by LukasCBossert** [comment]
```
\documentclass{scrartcl}
\usepackage[backend=biber,
style=archaeologie]{biblatex}
\addbibresource{archaeologie-examples.bib}

\AtBeginDocument{%
  \ifbool{bbx:initials}{%http://tex.stackexchange.com/a/295486/98739
  %%%---
  \ifbiberversion=>{2.11}
  %%%---
    {}
    {\DeclareStyleSourcemap{%
      \maps[datatype=bibtex]{%
        \map{%
          % Author field
          \step[fieldsource=author,%
            match={\regexp{\b(Chr|Ch|Th|Ph|St)(\S*,)}},%
            replace={\regexp{\{$1\}$2}}]% Protect last names (first last)
          \step[fieldsource=author,%
            match={\regexp{([^,]\s)\b(Chr|Ch|Th|Ph|St)}},%
            replace={\regexp{$1\{$2\}}}]% Protect last names (last, first)
          \step[fieldsource=author,%
            match={\regexp{\b(Chr|Ch|Th|Ph|St)([^\}])}},%
            replace={\regexp{\{\\relax\{\}$1\}$2}}]% Insert \relax after abbreviating
          % Editor field
          \step[fieldsource=editor,%
            match={\regexp{\b(Chr|Ch|Th|Ph|St)(\S*,)}},%
            replace={\regexp{\{$1\}$2}}]% Protect last names (first last)
          \step[fieldsource=editor,%
            match={\regexp{([^,]\s)\b(Chr|Ch|Th|Ph|St)}},%
            replace={\regexp{$1\{$2\}}}]% Protect last names (last, first)
          \step[fieldsource=editor,%
            match={\regexp{\b(Chr|Ch|Th|Ph|St)([^\}])}},%
            replace={\regexp{\{\\relax\{\}$1\}$2}}]% Insert \relax after abbreviating
        }}
      }
    }%
  }
  {}}
  
\begin{document}
%  \nocite{*}
\citeauthor{Mann2011}
  \footcite{Mann2011}
  \printbibliography
\end{document}
```

**Comment by moewew** [comment]
Ich würde die Option lieber ersatzlos streichen. Das bringt sonst Leute nur auf dumme Gedanken, wie Biber manuell downgraden oder `biblatex` nicht zu aktualisieren.

Die genutzte Biber-Version kannst Du aus TeX heraus nicht abfragen (zumindest nicht ohne Weiteres wie shell escape). Prinzipiell könnte man die `.bbl`-, `.bcf`- oder die `biblatex`-Version nutzen, all diese Versionen hängen aber nur mittelbar mit der Biberversion zusammen. Sie erlauben es nicht in allen Fällen, die Biberversion eindeutig festzulegen. So sollten offiziell nur `biblatex` 3.11 und Biber 2.11 zusammen betrieben werden, aber `biblatex` 3.11 funktioniert weitestgehend auch mit Biber 2.10 (wenn ich mich nicht irre), denn weder die BCF-Version noch die BBL-Version hat sich von `biblatex` 3.10 zu 3.11 geändert.

**Comment by LukasCBossert** [comment]
ok, dann werde ich mich (etwas wehmütig) von der Option trennen.

Ja, das wäre auch mein nächster GEdanke gewesen, die `biblatex`-Version als Abfrage zu nehmen. Aber du hast recht, lieber mit der Zeit und Technik gehen und nicht rückständige Optionen bereithalten.
