### ISSUE TITLE
Leerzeichen in postnote zwischen Kommata

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#151]
Ich vermute, dass diese "zusätzlichen" Leerzeichen von biblatex her kommen?
Wie kann ich das zurück ändern, dass es `12,23,45` heißt, @moewew ?

<img width="1072" alt="Bildschirmfoto 2019-04-29 um 23 57 12" src="https://user-images.githubusercontent.com/12896078/56930405-d7f4ba00-6adc-11e9-9234-f08470076b21.png">

```
\documentclass{scrartcl}
\usepackage{filecontents,csquotes}
\begin{filecontents*}{\jobname.bib}
 @inreference{Muller,
 author = {M{\"u}ller, Hildegund},
 title = {Ennarationes in Psalmos. A. Philologische Aspekte},
 pages = {804--838},
 volume = {2},
 booktitle = {AL-kurz},
 date = {1996/2002}
}
\end{filecontents*}

\usepackage[
  backend=biber,
  style=archaeologie,
 ]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\cite[12,23,45]{Muller}
\printbibliography
\end{document}

```

**Comment by moewew** [comment]
Ja, das kommt von `\mknormrange`. Du kannst diese Normalisierung ausschalten
```latex
\DeclareFieldFormat{postnote}{#1}
\DeclareFieldFormat{multipostnote}{#1}
```
aber dann wird auch `2-4` nicht mehr zu `2--4` umgewandelt.

Ansonsten kannst Du für Einzelfälle das Parsen mit `{}` unterdrücken
```latex
\cite[12{,}23{,}45]{Muller}
```

Eine andere Idee wäre
```latex
\renewrobustcmd*{\bibrangessep}{,}
```
aber das hat dann Auswirkungen auf all solche Seitenbereiche also z.B. auch auf
```latex
\cite[12,23,45]{Muller}
\cite[12, 23, 45]{Muller}
\cite[12-23, 45]{Muller}
```

**Comment by LukasCBossert** [comment]
Vielen Dank – ich werde es aber für `archaeologie` wohl nicht ändern, weil man dann ja diese schöne Vereinheitlichung nicht mehr hat. Die Anwender mögen im Falle es lokal überschreiben.
