### ISSUE TITLE
@Strings / Support for greek letters / inputenc

### ISSUE THREAD

**Issue by lsteinmann** [LukasCBossert/biblatex-archaeologie#153]
Hi! 
More a note than a real issue: Considering there are titles containing greek script in the `@String` macros it would be nice to remind people of adding some support for greek input letters in their preamble. I couldn't find anything in the readme.

(In case anyone encounters that problem: Everything should work fine with using \usepackage{textalpha} from [greek-fontenc](http://ctan.math.utah.edu/ctan/tex-archive/language/greek/greek-fontenc/README.html).)

(Danke übrigens fürs Bereitstellen, ist ein großartiges Paket!)

**Comment by LukasCBossert** [comment]
Hello Lisa,

thank you very much for the feedback and the remark! Somehow I never encountered that problem since I am always using `lualatex` and a font that covers most of the greek signs. However I will put in a note into the readme/introduction.

If you have any further remarks don’t hesitate.
