### ISSUE TITLE
'Make install' keeps failing

### ISSUE THREAD

**Issue by MBetulus** [LukasCBossert/biblatex-archaeologie#154]
Hi,
I have the following problem when trying to run
`make install` on Manjaro / Arch:

`@echo -e  <biblatex-archaeologie> * everything is up to date * 
sudo mkdir -p /usr/local/share/texmf:/usr/share/texmf/{tex,source,doc}/latex/biblatex-archaeologie
[sudo] Passwort für XXX: 
sudo mkdir -p /usr/local/share/texmf:/usr/share/texmf/bibtex/bib/biblatex-archaeologie
sudo cp archaeologie.{dtx,ins} /usr/local/share/texmf:/usr/share/texmf/source/latex/biblatex-archaeologie
cp: der Aufruf von stat für 'archaeologie.ins' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
make: *** [Makefile:63: install] Fehler 1`

I managed to make it work before. Anything I should try? Do you need additional infos? I'm trying to use the package in Lyx.

Thank you :)

**Comment by LukasCBossert** [comment]
This is odd. Unfortunately I cannot reproduce the error. the ins-file is generated from the dtx-file and should be there. 

Try

```
	sudo cp -v $(NAME).{dtx,ins} $(LOCAL)/source/latex/$(PFX)$(NAME)
```
This might give more information. 

Using the style with LyX shouldnt be the problem.

**Comment by MBetulus** [comment]
I tried running
`make install`
after deleting the line
`sudo cp $(NAME).{dtx,ins} $(LOCAL)/source/latex/$(PFX)$(NAME)`
from the Makefile, this was the result:
`@echo -e  <biblatex-archaeologie> * everything is up to date * 
sudo mkdir -p /usr/local/share/texmf:/usr/share/texmf/{tex,source,doc}/latex/biblatex-archaeologie
sudo mkdir -p /usr/local/share/texmf:/usr/share/texmf/bibtex/bib/biblatex-archaeologie
sudo cp archaeologie.{b,c,d}bx {english,german,italian,french,spanish}-archaeologie.lbx /usr/local/share/texmf:/usr/share/texmf/tex/latex/biblatex-archaeologie
cp: der Aufruf von stat für 'archaeologie.bbx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'archaeologie.cbx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'archaeologie.dbx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'english-archaeologie.lbx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'german-archaeologie.lbx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'italian-archaeologie.lbx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'french-archaeologie.lbx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'spanish-archaeologie.lbx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
make: *** [Makefile:63: install] Fehler 1

It doesn't seem to find anything?

Then I tried to run
`make files`
first, lots of files are created until the installer can't find some *.sty:
`! LaTeX Error: File `libertine.sty' not found.`

Does the installer have some prerequisites I need to install first?

Oddly enouh, as I already mentioned, I managed to make this package work very successfully a few times before.

**Comment by MBetulus** [comment]
It did not seem to work. Bibliography stays empty; Footnotes are unformatted (e.g. smith2002). 
Maybe I should try a clean, new install?

**Comment by MBetulus** [comment]
Alright, a clean, new install of all Tex packages and Lyx seems to have fixed the missing dependencies.
Still, `make install` by itself is not working for me. I need to do the following order:
`make files`
Cancel with X after the first missing file (libertine.sty)
`make install`

Here is my system:

Manjaro Linux
KDE-Plasma-Version: 5.20.5
KDE-Frameworks-Version: 5.78.0
Qt-Version: 5.15.2
Kernel-Version: 5.10.7-3-MANJARO

**Comment by MBetulus** [comment]
Compiling of the documents works now, but I still get some minor errors:

![Screenshot_20210208_095328](https://user-images.githubusercontent.com/59888848/107197108-c64f7e80-69f3-11eb-8ff4-5a15d12e34ba.png)

**Comment by LukasCBossert** [comment]
glad that the installation worked now - otherwise I would have no idea what it could be.

I will change the default of `make` so it will make `make files` first.


regarding the weird error from the screenshot. it looks like LyX is complaining about `%*Abweichung!` . I will delete those from the master file.
