### ISSUE TITLE
Put "submitted" in parentheses in the text

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#156]
According to 
https://tex.stackexchange.com/questions/694028/for-unpublished-works-print-pubstate-field-in-parentheses-for-in-text-citation there is a wrongly defined `labeldatesource`.

Solution already provided by @moewew 
https://tex.stackexchange.com/a/694037/98739

**Comment by LukasCBossert** [comment]
haha - ok, this is not as easy as I thought since I first need to fix other issues that comes with general mainaining the `ltx`

- ´! Package cleveref Error: cleveref must be loaded after amsmath!.`
- `! LaTeX Error: Can be used only in preamble.`

**Comment by lukeflo** [comment]
Moin
cool auf jeden Fall, dass du die Änderung so fix vornimmst. Bin mir gar nicht 100 % sicher, ob das in den DAI Richtlinien so gewollt ist, aber es macht die Sache auf jeden Fall deutlicher, wenn `labeldatesource` nicht aus Zahlen besteht.
LG

**Comment by LukasCBossert** [comment]
hi, die DAI-Richtlinien äußern sich nicht zu Werken mit solch einem Publikationsstatus. Daher kann man das ruhig aufnehmen.

**Comment by LukasCBossert** [comment]
hm - ich denke, ich weiß, warum ich das damals ohne Klammern programmiert hatte. Um deinen gewünschten Output im Fließtext zu erzeugen, reicht es, wenn man `\textcite` nimmt. 
Man würde wahrscheinlich auch nicht ´\cite` im Fließtext verwenden, womit man den Querverweis auf den Publikationseintrag bekommt, sondern im Fließtext würde man eher die Autorennamen erwähnen und in Klammer dann die Jahreszahl bzw. Jahreszahl+Buchstabe. @lukeflo

**Comment by LukasCBossert** [comment]
@lukeflo Du schreibst auf stackexchange, dass bei `\finentrypunct` der Schlusspunkt fehlt, weswegen du vorschlägst:
```
\renewcommand{\finentrypunct}{\adddot} 
```

Soweit ich sehe, ist der Schlusspunkt jedoch *nicht* Teil der DAI-Zitierrichtlinie:
https://www.dainst.org/documents/10180/70593/01_Schlagwortliste_quer.pdf/60686d03-44a0-4fc0-a614-136c50257a12

**Comment by lukeflo** [comment]
> hm - ich denke, ich weiß, warum ich das damals ohne Klammern programmiert hatte. Um deinen gewünschten Output im Fließtext zu erzeugen, reicht es, wenn man `\textcite` nimmt. Man würde wahrscheinlich auch nicht ´\cite` im Fließtext verwenden, womit man den Querverweis auf den Publikationseintrag bekommt, sondern im Fließtext würde man eher die Autorennamen erwähnen und in Klammer dann die Jahreszahl bzw. Jahreszahl+Buchstabe. @lukeflo

Das kann durchaus sein. Für den Workflow den ich aktuell programmiere, wird allerdings nur auf das klassische `cite` zurückgegriffen, da die LaTeX Dateien anschließen u.a. mit Pandoc weiterverarbeitet werden müssen. Da führen die etwas "ungewöhnlichsten" cite commands hin und wieder zu unentwünschten Ergebnissen im finalen Output.

**Comment by lukeflo** [comment]
> @lukeflo Du schreibst auf stackexchange, dass bei `\finentrypunct` der Schlusspunkt fehlt, weswegen du vorschlägst:
> 
> ```
> \renewcommand{\finentrypunct}{\adddot} 
> ```
> 
> Soweit ich sehe, ist der Schlusspunkt jedoch _nicht_ Teil der DAI-Zitierrichtlinie: https://www.dainst.org/documents/10180/70593/01_Schlagwortliste_quer.pdf/60686d03-44a0-4fc0-a614-136c50257a12

Haha. Das Comment hinter dem Befehl war eigentlich nur für mich selber gedacht. Vergessen zu löschen. Für besagte cls file benötige ich eine in manchen Punkten leicht adaptierte Variante der DAI Zitierrichtlinien mit Punkt am Ende. Habe aber den Kommentar bei stack exchange entfernt, um nicht den Eindruck zu erwecken, dass dee Fehler bei deinem Paket liegt ;)

**Comment by LukasCBossert** [comment]
ok, verstehe @lukeflo . Ich frage mich dann, ob es dann eine Änderung am `archaeologie`-Stil rechtfertigt. Die `fineentrypunct`-Sache ist geklärt, das würde ich nicht ändern. 
Der andere Punkt liegt dann nicht so sehr an der Verwendung von `\cite` bzw. `\textcite` , sondern ob man die Angabe von `pubstate` an sich in Klammer haben möchte; für den Fließtext ist das sinnig, für die Bibliografie wahrscheinlich Ansichtssache.
Kannst du eine Beispielpassage nennen, bei der du `cite` mit einem normalen Eintrag verwendest? Ich würde davon ausgehen, dass dies auch komische Nebeneffekte erzeugt, bzw. die Lesbearbeit einschränkt, wenn dann steht: 
> .... das sieht ja auch schon Schließmann 1876c, als er behauptet, Troja gefunden zu haben.

Hier würde ich auch davon ausgehen, dass man das `labeldate` in Klammern haben möchte?!

**Comment by lukeflo** [comment]
@LukasCBossert da muss ich zwischen meinen persönlichen Präferenzen und den Vorgaben der Journals unterscheiden, für die das Template später ggf. zum Einsatz kommen soll.

Ich selbst würde intext eher mit `\citeauthor*{Schliemann1896}` zitieren und das author-year Kurzzitat mit Seitenzahl in eine Fußnote packen.

Wie es genau bei den Journals aussieht, muss ich morgen nochmal konkret schauen. Aber ich glaube, es war ähnlich wie in deinem Beispiel, weshalb ich eben `label`, die durch ein Wort bzw. einen `string` repräsentiert werden in Klammern setzen wollte, um diese deutlicher vom Fließtext abzuheben. Das geschieht bei Jahreszahlen ja etwas selbstverständlicher. Aber, wie gesagt, werde das morgen checken.

Abgesehen davon, hätte ich großes Interesse, mich auch mal etwas detaillierter bzgl. Nutzung/Chancen von LaTeX in Fachgebieten wie eben Archäologie/Altertumswissenschaften auszutauschen; falls du da auch Interesse hättest. Allzu viele Gesinnungsgenossen gibt es da ja leider bisher nicht...

Schönen Restabend noch!

**Comment by lukeflo** [comment]
Habe gerade nochmal nachgeschaut. Leider scheinen die Formatierungsvorgaben für die Open-Access Journals des DAI noch etwas uneinheitlicher zu sein bzw. inkonsequenter umgesetzt zu werden als gedacht.

In manchen Beiträgen werden die Kurzzitate im Fließtext in Klammern getätigt, viele andere wiederum zitieren nur in den Fußnoten und nennen im Fließtext lediglich den Autorennamen; manche kombinieren das auch, etwa so `... nach Schliemann (Schliemann 1896) soll dies...`, was irgendwie sehr doppelt gemoppelt wirkt.

Leider konnte ich bisher keinen Beitrag finden, der explizit noch nicht veröffentlichte Beiträge zitiert. Hier steht also ein Nachweis noch aus. Ich denke aber nach wie vor, dass solche Kurzzitate den Hinweis `submitted` einklammern sollten, damit keine grammatikalischen Uneindeutigkeiten entstehen.

Auch bezüglich des Punktes am Ende der Bibliographieeinträge herrscht in den Journals keine Einheit. Die Mehrzahl setzt keinen Punkt als finalen Delimiter, wie du es auch korrekt angemerkt hast. Einige dann aber wieder doch, v.a. eben das Journal meiner Einrichtung, welches als Hauptvorlage für meine `cls` Datei dient. 

Ich habe auch noch weitere Unstimmigkeiten gefunden: So wird etwa die Punktuation vor den Seitenzahlen im Kurzzitat anscheinend ebenfalls unterschiedlich angewendet. Einige zitieren `Schliemann 1986: 345`, andere wiederum `Schliemann 1986, 345`. Werde da wohl nochmals genauer recherchieren müssen.

Ob du nun die Klammern für einen möglichen `pubstate` Eintrag als `labeldatesource` übernehmen solltest, ist demnach bisher nicht abschließend anhand der Vorgaben und der Praxis zu belegen. Ich würde es so handhaben und auch empfehlen, aber das bleibt meine persönliche Meinung... ;)

**Comment by LukasCBossert** [comment]
Ok, das ist also alles nicht sehr einheitlich. Ich kann `labeldatesource` in Klammern setzen – was vom DAI nicht explizit vorgegeben ist, liegt dann im Ermessensspielraum des Autors. 

bzgl. Austausch, schick mir eine direkte Email.

**Comment by lukeflo** [comment]
Alles klar. Ich denke, es ist kein Muss. Kommt halt auch drauf an, wie viel Aufwand für dich dahinter steckt. Wirklich häufig kommt der Fall anscheinend nicht vor. Eventuell als package option wie `pubstate=parantheses`, dann kann es jeder selbst entscheiden. Für mich geht es auch mit den paar Zeilen extra Code direkt in der `cls`.

An welche Mail soll ich mich denn wenden. Die hier von GitHub?

**Comment by LukasCBossert** [comment]
nimm die hier: https://www.itc.rwth-aachen.de/cms/it-center/IT-Center/Profil/Team/~epvp/Mitarbeiter-CAMPUS-/?gguid=0x741F3A251551044BB9047AF649DED3B4&allou=1
