### ISSUE TITLE
Option "dai-footnote" / "seenote" Rückverweis auf Fußnote mit Vollzitat

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#29]
Zitation in Fußnoten nur die erste Fußnote Vollzitat, danach Verweis. 
Vgl. Stil "geschichtsfrkl"

**Comment by moewew** [comment]
Der Standardstil `verbose-note` implementiert so etwas in der Art, es muss aber dann wirklich `\footcite` genutzt werden und nicht `\footnote{\cite{sigfridsson}}`. Ich denke, dass lässt sich recht einfach übernehmen.

**Comment by LukasCBossert** [comment]
hm. da sehe ich aber eine Schwierigkeit, da Altertumswissenschaftler gerne noch ausführlich(er) in den Fußnoten auf bestimmte Aspekte eingehen, sodas `\footcite`dafür nicht genutzt werden kann.

**Comment by moewew** [comment]
Kommando zurück! `verbose-note` ist so klug, zu erkennen, ob man in einer Fußnote ist oder nicht und dann das richtige Makro zu nutzen, das heißt auch `\footnote{\cite{sigfridsson}}` funktioniert tadellos.

**Comment by LukasCBossert** [comment]
aha! ich kannte bei den beispielen immer nur `\footnote{sigfridsson}`- aber jetzt ist das eine andere Sache.

**Comment by LukasCBossert** [comment]
Die Option wurde in `seenote` umbenannt und ist lauffähig.
Es kann nun getestet werden.
`\textcite` ist gleich wie `\cite` da es ansonsten bei der Option `seenote` wenig Sinn ergibt.

<img width="836" alt="bildschirmfoto 2016-05-16 um 18 43 41" src="https://cloud.githubusercontent.com/assets/12896078/15296579/3f280464-1b96-11e6-9e27-2ae1908c0f7b.png">

**Comment by LukasCBossert** [comment]
Generelles Problem dieser Zitierweise: Wenn zwei Einträge eines Autors in einer Fußnote zum ersten Mal zitiert werden, wird es unklar sein, auf welchen Eintrag später bezogen wird.

Wie kann man das lösen?

**Comment by LukasCBossert** [comment]
Lösung des Problems liegt in der Aufnahme des `title`, bzw. `shorttitle` (mit einem `ifequal`??)
Da Jahreszahlen hier nicht funktionieren, würden wir einen Kurztitel nutzen, z.B. "Hölscher, Öffentliche Räume a. O." und "Hölscher, Frühzeit a. O.".

**Comment by LukasCBossert** [comment]
Problem in der `cbx` bei Einträgen mit `option=corpus`, dann wird die `shorthand` nicht mit ausgegeben, sondern nur `year`, bzw. `title`.

**Comment by LukasCBossert** [comment]
War kein Fehler.

**Comment by LukasCBossert** [comment]
Merge into https://github.com/LukasCBossert/biblatex-archaeologie/commit/ebb4f43896a291a42e1d2555625bd2163c4a497e
