### ISSUE TITLE
Angabe der Reihe von antiken Werken in der Shorthand

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#32]
Wenn man bspw. auf verschiedene Übersetzungen eingeht, wäre es sinnvoll in der Kurzzitation nach der Postnote die Reihe oder den Übersetzer stehen zu haben:

> "spectacle" in Vitr. 5,1,2 (Loeb); wohingegen "Schauplatz" bei Vitr. 5,1,2 (Fensterbusch)

vielleicht kann man das mit einer cbx-Option versehen, sodass man diese Angabe steuern kann. Dabei müssten sich auch die Shorthands für die Bibliographie ggf. ändern:

- Vitr. (Loeb)     XXX
- Vitr. (Fensterbusch)    XXX
- Vitr. (Morgan)    XXX

**Comment by giovannotti** [comment]
Macht es nicht sowieso Sinn, die shorthand auf diese Art zu definieren, wenn man mehrere Textausgaben zu einem Text hat? Ansonsten würden die ja in der Bibliographie allesamt als Vitr. erscheinen. Die Frage ist nur, was man macht, wenn man ja nur auf Vitruv allgemein verweisen will:
Im schlimmsten Fall manuell und nicht über einen cite-Befehl... das wird dir aber nicht gefallen :-)
Idee?

**Comment by LukasCBossert** [comment]
in der Tat habe ich es jetzt so gemacht, dass ich die shorthands entsprechend gestaltet habe:

  Shorthand                = {Vitr. (Loeb)},

nur, rein optisch wäre es schöner, wenn dann in der Ausgabe stünde: Vitr. 1,7,1 (Loeb) - dazu müsste man die \postnote zwischen Antikem Autor und Ausgabe klemmen. An sich passiert sowas bei "frgantik" - werde dort nochmals nachschauen.

**Comment by LukasCBossert** [comment]
sodele, habe was gewerkelt. Weiß noch nicht, ob es gut ist.

Ich habe mich entscheiden eine (weitere) Option einzubauen `cbx:antiktranslator` erst wenn diese aktiviert ist, werden die Übersetzer der antiken Werke hinter die `postnote`angegeben 

```
\DeclareBibliographyOption{antiktranslator}[true]{\csuse{bool#1}{cbx:antiktranslator}}%

\renewbibmacro*{postnote}{%
  \ifboolexpr{bool {cbx:antik}%
              or bool {cbx:frgantik}%
              or bool {cbx:nurshorthand}%
              }%
    {\setunit{\addspace}}%
    {\newunit}%
  \iffieldundef{postnote}
    {}%
    {\printfield{postnote}%
     \ifbool{cbx:frgantik}%
       {\setunit{\addspace}%
        \ifnameundef{shorteditor}%
           {\printnames[frg]{editor}}%
           {\printnames[frg]{shorteditor}}}%
       {\ifbool{cbx:antiktranslator}{\addspace%
       \mkbibparens{\bibstring{translated}\addspace\printnames[frg]{translator}}}}%
       {}%
 }%
 }

```

dann wird aus `\cite[1, 3,3]{Cic_Att}` --> Cic. Att. 1, 3,3 (übers. v. Kasten)

**Comment by giovannotti** [comment]
dann geht es nur global, oder?
Bei mir macht er es aber auch bei ganz anderen Postnotes, probier mal so ein Postnote zu `cosa_1949`.

**Comment by LukasCBossert** [comment]
mist, ich glaube, ich habe da ein Denkfehler drin gehabt....Mir hat es eh nicht gut gefallen, dass es global gelöst ist. es müsste von selbst schauen, ob der gleiche antike Autor in einer oder zwei verschiedenen Übersetzungen vorliegt und nur dann den Übersetzer angeben.

**Comment by LukasCBossert** [comment]
Habe es erstmal wieder zurückgebaut.

**Comment by LukasCBossert** [comment]
Könnte vielleicht mit `\iffieldsequal{⟨field 1⟩}{⟨field 2⟩}{⟨true⟩}{⟨false⟩}` bzw. `\iffieldequals{⟨field⟩}{⟨macro⟩}{⟨true⟩}{⟨false⟩}` abgefragt werden.
Für `true` muss dann nach der `postnote` den `translator` eingefügt werden, wenn der nicht angegeben ist, dann der `editor`.
Zugleich ändert sich aber dann das `label` für die Bibliographie, das `translator`bzw. `editor` beigefügt bekommt.

**Comment by giovannotti** [comment]
Vielleicht bringt uns das Paket `classics` auf interessante Gedanken, wobei ich selbst noch nicht genau darüber nachgedacht habe. Aber die Verknüpfung von einem antiken Autor mit 1...n Sekundärautoren ist ja genau das, was wir bräuchten. Ich weiß allerdings nicht, was die unterste Code-Zeile dann anzeigt (Bibliographie, Zitat, etc.).

Hast du das Paket schon mal getestet? Der Post ist aus StackExchange:

>You may use the classics package to typeset Bekker pages too:
>
>![image](https://cloud.githubusercontent.com/assets/10049662/15529874/da98f88e-2250-11e6-9579-d684f563fc9f.png)
>    
    \documentclass{article}
    \usepackage{classics}
    \newclassic{Aristotle}{#1|\textit{#1}|#1}
>
    \begin{document}
    \Aristotle [Met.]{1048}[a]
>
    \Aristotle [Met.]{1048}[a][36]
>
    \Aristotle*[Met.]{1048}[a][36]{1049}[b][37]
>
    \end{document}
>And this is how to use it with biblatex:
>
    \cite[{\Aristotle{1048}[a][36]}]{ross1924}


http://tex.stackexchange.com/questions/31286/how-do-i-cite-classical-works-with-biblatex/310778

**Comment by LukasCBossert** [comment]
Hey,

ich habe das Paket schon „gesehen“, aber ich finde unsere Lösung intuitiver und stringenter. Denn man muss ja für jedes antike Autoren-Zitat zuerst ein \newclassic definieren. 
Unsere Lösung ist ja auch mit (einem) Sekundärautor verknüpft - für mehrere kann man sich mehrere Bibliographieeinträge definieren?

Mir ist der Vorteil von classics noch nicht ganz klar.


---
Lukas C. Bossert

http://hu-berlin.academia.edu/LukasCBossert
http://github.com/LukasCBossert

**Comment by LukasCBossert** [comment]
Ah, du hast es hier gepostest :-) 

Dennoch würde ich eher den Weg vorschlagen über ein `\ifequal{shorthand}`  und dann analog zur `postnote` von `frgancient` die `series` oder `translator` anzugeben.

**Comment by LukasCBossert** [comment]
Ein neuer Versuch:
Man betrachte folgendes MWE:
```
\documentclass[ngerman]{scrbook}
\usepackage{babel}
\usepackage{libertine}
\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}

@Book{Vitr,
  author        = {Vitruvius},
  title         = {Zehn Bücher über Architektur},
  publisher     = WBG,
  location      = {Darmstadt},
  year          = {2008},
  edition       = {6},
  origyear      = {1964},
  origtitle     = {De architectura},
  origlanguage  = {latin},
  translator    = {Fensterbusch, Curt},
  shorthand     = {Vitr.},
  shortauthor   = {Vitruv},
  keywords      = {ancient},
  options       = {ancient},
  authoraddon   = {Vitruvius},
  sortshorthand = {Vitr.},
  timestamp     = {2015-12-14},
}

@Book{Vitr_loeb,
  author        = {Vitruvius},
  title         = {On Architecture},
  publisher     = HUP,
  location      = {Cambridge and London},
  year          = {1983},
  volume        = {I--II},
  series        = {Loeb Classical Library},
  number        = {251},
  origyear      = {1931},
  origtitle     = {De architectura},
  origlanguage  = {latin},
  translator    = {Granger, Frank},
  shorthand     = {Vitr.},
  shortauthor   = {Vitruv},
  keywords      = {ancient},
  options       = {ancient},
}

@Book{Vitr_Prestel,
  author       = {Vitruvius},
  title        = {Zehn Bücher über Architektur des Marcus Vitruvius Pollio},
  publisher    = {Heitz \& Mündel},
  location     = {Strassburg},
  year         = {1912},
  series       = {Zur Kunstgeschichte des Auslandes},
  number       = {100},
  origlanguage = {latin},
  translator   = {Prestel, J.},
  shorthand    = {Vitr.},
  keywords     = {ancient},
  options      = {ancient},
}

@inBook{Vitr_Rode,
  author        = {Vitruvius},
  title         = {Des Marcus Vitruvius Pollio Baukunst},
  publisher     = {bey Georg Joachim Göschen},
  location      = {Leipzig},
  year          = {1796},
  volume        = {I},
  booktitle = {Vitruv},
  origtitle     = {De architectura},
  origlanguage  = {latin},
  intranslator    = {August Rode},
  shorthand     = {Vitr.},
  shortauthor   = {Vitruv},
  keywords      = {ancient},
  options       = {ancient},
}

@Book{Vitr_Rowland,
  author       = {Vitruvius},
  title        = {Vitruvius},
  subtitle     = {Ten Books on Architecture},
  publisher    = CUP,
  location     = {Cambridge},
  year         = {1999},
  origtitle    = {De architectura},
  origlanguage = {latin},
  translator   = {Rowland, Ingrid D.},
  shorthand    = {Vitr.},
  shortauthor  = {Vitruv},
  keywords     = {ancient},
  options      = {ancient},
  file         = {:Quellen/Vitruv/Vitruvius_(Vitr_Rowland)_Vitruvius.pdf:PDF},
  groups       = {Literarische Konzeption: Vitruv},
  owner        = {Lukas C. Bossert},
  timestamp    = {2015-09-28},
}

@Book{Vitr_Saliou,
  author       = {Vitruvius},
  title        = {De L'Architecture},
  publisher    = {Les belles lettres},
  location     = {Paris},
  volume       = {I--X},
  series       = {Collection des Universités de France},
  origtitle    = {De architectura},
  origlanguage = {latin},
  translator   = {Saliou, Catherine},
  shorthand    = {Vitr.},
  shortauthor  = {Vitruv},
  keywords     = {ancient},
  options      = {ancient},
  date         = {1986/2009},
}

@Book{Vitr_Smith,
  author       = {Vitruvius},
  title        = {Vitruvius on Architecture},
  publisher    = {The Monacelli Press},
  location     = {New York},
  year         = {2003},
  origtitle    = {De architectura},
  origlanguage = {latin},
  translator   = {Smith, Thomas Gordon},
  shorthand    = {Vitr.},
  shortauthor  = {Vitruv},
  keywords     = {ancient},
  options      = {ancient},
}

@Incollection{Verg_georg,
  author         = {Vergilius Maro, Publius},
  title          = {Landbau},
  pages          = {84--209},
  editor         = {Götte, Johannes and Götte, Maria and Bayer, Karl},
  booktitle      = {Landleben},
  intranslator = {Hans Wurst},
  booksubtitle   = {Catalepton, Bucolica, Georgica},
  publisher      = AWi,
  location       = {Zürich},
  year           = {1995},
  series         = {Sammlung Tusculum},
  edition        = {6},
  origlanguage   = {latin},
  options        = {ancient},
  keywords       = {ancient},
  booktitleaddon = {Vergil-Viten},
  shortauthor    = {Vergil},
  shorthand      = {Verg. georg.},
}

\end{filecontents*}
\usepackage{csquotes}
\usepackage[           
  backend=biber,
  style=../biblatex-archaeologie/archaeologie,
]{biblatex}

\newbibmacro*{uniqueshorthand}{%
\ifboolexpr{%
      bool {cbx:ancient}%
      or bool {cbx:frgancient}}%
    {\ifnameundef{translator}%
      {\ifnameundef{intranslator}%
        {\iffieldundef{series}
          {\printfield[parens]{series}}
          {\printname[parens]{editor}}}
        {\printname[parens]{intranslator}}%
    }%
   {\printname[parens]{translator}}%
  }%
  {}%
  }%


\renewbibmacro*{cite:shorthand}{%
  \ifbool{cbx:seenote}%
  {\printtext{\printfield{shorthand}}}%
  {\printtext[bibhyperref]{%
\iffieldequalcs{shorthand}{shorthand}%< Kasus knaxsus
  {\printfield{shorthand}\addspace
    \usebibmacro*{unqiueshorthand}}%
 {\printfield{shorthand}}%
}}%
}


\addbibresource{\jobname.bib}
\begin{document}
\footnote{\cite{Verg_georg}}
\footnote{\cite{Vitr,Vitr_loeb,Vitr_Prestel,Vitr_Rode,Vitr_Rowland,Vitr_Saliou,Vitr_Smith}}
\footnote{\cite[vgl.][234]{Vitr}}
\footnote{\cites[vgl.][34]{Vitr_loeb}[56]{Vitr_Prestel}{Vitr_Rode}}
\footnote{\cites(vgl.)()[s.][89]{Vitr_Rowland}{Vitr_Saliou}[90]{Vitr_Smith}}

  \nocite{*}
  \printbibliography
\end{document}
```

Die Einträge der antiken Werke sind in der Fußnote immer mit `Vitr.` angegeben, obwohl es sich um verschiedene Werke/Buchausgaben handelt. 
Ziel und Wunsch ist es, dass hinter die `shorthands` im Falle einer ›Gleichheit‹ der Übersetzer/Serie in Klammer mit ausgegeben wird.

Mir scheint bei meinem Versuch das Problem in Zeile 180 zu liegen:
`\iffieldequalcs{shorthand}{shorthand}%< Kasus knaxsus` 
Welchen Code muss man wählen, dass geschaut wird, ob ein Feld einzigartig ist, @moewew ?

**Comment by LukasCBossert** [comment]
Mit diesem MWE bekomme ich schon ein annehmbares Ergebnis:
```
\documentclass[ngerman]{scrbook}
\usepackage{babel}
\usepackage{libertine}
\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}

@Book{Vitr,
  author        = {Vitruvius},
  title         = {Zehn Bücher über Architektur},
  publisher     = WBG,
  location      = {Darmstadt},
  year          = {2008},
  edition       = {6},
  origyear      = {1964},
  origtitle     = {De architectura},
  origlanguage  = {latin},
  translator    = {Fensterbusch, Curt},
  shorthand     = {Vitr.},
  shortauthor   = {Vitruv},
  keywords      = {ancient},
  options       = {ancient},
  authoraddon   = {Vitruvius},
  sortshorthand = {Vitr.},
  timestamp     = {2015-12-14},
}

@Book{Vitr_loeb,
  author        = {Vitruvius},
  title         = {On Architecture},
  publisher     = HUP,
  location      = {Cambridge and London},
  year          = {1983},
  volume        = {I--II},
  series        = {Loeb Classical Library},
  shortseries = {Loeb},
  number        = {251},
  origyear      = {1931},
  origtitle     = {De architectura},
  origlanguage  = {latin},
  shorthand     = {Vitr.},
  shortauthor   = {Vitruv},
  keywords      = {ancient},
  options       = {ancient},
}

@Book{Vitr_Prestel,
  author       = {Vitruvius},
  title        = {Zehn Bücher über Architektur des Marcus Vitruvius Pollio},
  publisher    = {Heitz \& Mündel},
  location     = {Strassburg},
  year         = {1912},
  series       = {Zur Kunstgeschichte des Auslandes},
  number       = {100},
  origlanguage = {latin},
  translator   = {Prestel, J.},
  shorthand    = {Vitr.},
  keywords     = {ancient},
  options      = {ancient},
}

@inBook{Vitr_Rode,
  author        = {Vitruvius},
  title         = {Des Marcus Vitruvius Pollio Baukunst},
  publisher     = {bey Georg Joachim Göschen},
  location      = {Leipzig},
  year          = {1796},
  volume        = {I},
  booktitle = {Vitruv},
  origtitle     = {De architectura},
  origlanguage  = {latin},
  intranslator    = {August Rode},
  shorthand     = {Vitr.},
  shortauthor   = {Vitruv},
  keywords      = {ancient},
  options       = {ancient},
}

@Book{Vitr_Rowland,
  author       = {Vitruvius},
  title        = {Vitruvius},
  subtitle     = {Ten Books on Architecture},
  publisher    = CUP,
  location     = {Cambridge},
  year         = {1999},
  origtitle    = {De architectura},
  origlanguage = {latin},
  translator   = {Rowland, Ingrid D.},
  shorthand    = {Vitr.},
  shortauthor  = {Vitruv},
  keywords     = {ancient},
  options      = {ancient},
  file         = {:Quellen/Vitruv/Vitruvius_(Vitr_Rowland)_Vitruvius.pdf:PDF},
  groups       = {Literarische Konzeption: Vitruv},
  owner        = {Lukas C. Bossert},
  timestamp    = {2015-09-28},
}

@Book{Vitr_Saliou,
  author       = {Vitruvius},
  title        = {De L'Architecture},
  publisher    = {Les belles lettres},
  location     = {Paris},
  volume       = {I--X},
  series       = {Collection des Universités de France},
  origtitle    = {De architectura},
  origlanguage = {latin},
  translator   = {Saliou, Catherine},
  shorthand    = {Vitr.},
  shortauthor  = {Vitruv},
  keywords     = {ancient},
  options      = {ancient},
  date         = {1986/2009},
}

@Book{Vitr_Smith,
  author       = {Vitruvius},
  title        = {Vitruvius on Architecture},
  publisher    = {The Monacelli Press},
  location     = {New York},
  year         = {2003},
  origtitle    = {De architectura},
  origlanguage = {latin},
  translator   = {Smith, Thomas Gordon},
  shorthand    = {Vitr.},
  shortauthor  = {Vitruv},
  keywords     = {ancient},
  options      = {ancient},
}

@Incollection{Verg_georg,
  author         = {Vergilius Maro, Publius},
  title          = {Landbau},
  pages          = {84--209},
  editor         = {Götte, Johannes and Götte, Maria and Bayer, Karl},
  booktitle      = {Landleben},
  intranslator = {Hans Wurst},
  booksubtitle   = {Catalepton, Bucolica, Georgica},
  publisher      = AWi,
  location       = {Zürich},
  year           = {1995},
  series         = {Sammlung Tusculum},
  edition        = {6},
  origlanguage   = {latin},
  options        = {ancient},
  keywords       = {ancient},
  booktitleaddon = {Vergil-Viten},
  shortauthor    = {Vergil},
  shorthand      = {Verg. georg.},
}

\end{filecontents*}
\usepackage{csquotes}
\usepackage[           
  backend=biber,
  style=archaeologie,
]{biblatex}

\newbibmacro*{uniqueshorthand}{%
\ifboolexpr{%
      bool {cbx:ancient}%
      or bool {cbx:frgancient}}%nur um sicher zu gehen,  nur bei antiken Werken 
    {%
% hier soll die Entscheidung gefällt werden, ob Feld shorthand einmalig ist: (\ifuniqueshorthand)?
    \printtext[brackets]{%
    	\ifnameundef{translator}
    	{\ifnameundef{intranslator}%
        	{\iffieldundef{series}%
      	{\printnames[name:family]{editor}}%
     	{\usebibmacro*{series}}}%
        {\printnames[name:family]{intranslator}}}%
    	{\printnames[name:family]{translator}}}%
  }%
{}%
}

\renewbibmacro*{cite:shorthand}{%
  \ifbool{cbx:seenote}%
  {\printtext{\printfield{shorthand}}}%
  {\printtext[bibhyperref]{\printfield{shorthand}%
    \addspace %
    \usebibmacro*{uniqueshorthand}}%
  }%
}


\addbibresource{\jobname.bib}
\begin{document}
\footnote{\cite{Verg_georg}}
\footnote{\cites{Vitr}{Vitr_loeb}{Vitr_Prestel}{Vitr_Rode}{Vitr_Rowland}{Vitr_Saliou}{Vitr_Smith}}
\footnote{\cite[vgl.][234]{Vitr}}
\footnote{\cites[vgl.][34]{Vitr_loeb}[56]{Vitr_Prestel}{Vitr_Rode}}
\footnote{\cites(vgl.)()[s.][89]{Vitr_Rowland}{Vitr_Saliou}[90]{Vitr_Smith}}

  \nocite{*}
  \printbibliography
\end{document}
```

Mir fehlt die Idee zu unterscheiden, ob das Feld `shorthand` bereits verwendet wurde oder nicht. Im Sinne eines `\ifuniqueshorthand` wie es `\ifuniquework` oder `\ifuniquetitle` ja gibt.
Dies ist wichtig, dass bei `Verg_georg` der Übersetzer nicht mit ausgegeben wird, denn die `shorthand` ist einmalig und somit der Zusatz unnötig.
Irgendwelche Ideen, @moewew ?

**Comment by moewew** [comment]
Soweit ich weiß, werden `\ifuniquework` und `\ifuniquetitle` von Biber bereitgestellt. Für `shorthand` gibt es wohl nichts dergleiches (die Idee ist wohl, dass shorthands immer unique sind).

Du kannst natürlich probieren, dir zu merken, welche shorthands schon benutzt wurden; aber damit kannst du nicht in die Zukunft sehen, und das müsstest du eigenlich können, damit das was wird. (Du müsstest ja schon beim ersten Auftreten von "Vitr." wissen, dass später noch ein anderer kommt, der ihn nicht mehr einzigartig macht.) Du *könntest* in die Zukunft sehen, wenn Du in die `.aux`-Datei schreibst, aber das ist ganz schön wiederlich, sich damit rumzuschlagen.

**Comment by LukasCBossert** [comment]
Schade, dass es kein `\ifuniqueshorthand` gibt, denn ich finde nicht, dass die immer unique sind. 
Ich nehme an, man kann so eine Abfrage nicht analog zu `\ifuniquework` bauen?

An sich wäre es auch in Ordnung wenn das erste Auftreten einer `shorthand` ›normal‹ bleibt (also nur die `shorthand`; bspw. von `\cite{Vitr}`) und erst bei einer anderen Erwähnung danach (bspw. `\cite{Vitr_loeb}`) die `shorthand` erweitert wird. 
Aber würde ja anders funktionieren als bei der Option `cbx:seenote`, wo es immer um denselben Datensatz geht.

**Comment by moewew** [comment]
Könnte man wohl schon, aber das müsste von Biber kommen, also müsstest Du einen Feature-Request starten. Mit Gefummel in `biblatex` allein ist es da nicht getan uns sind von der Seite die Hände gebunden.

Stimmt, da bräuchtest du eine Art zweidimensionales Array. Keine Ahnung, ob das geht, vielleicht mit `expl3`?

**Comment by LukasCBossert** [comment]
Ok, davon habe ich wirklich keine Ahnung.... Sieht mir also danach aus, dass ich von dieser Idee erstmal Abschied nehmen muss und die `shorthand`-Felder manuell mit der Erweiterung bestücken.

**Comment by LukasCBossert** [comment]
Heureka - fast. Ein Lösungsansatz mit `bool`:
```
\newbool{cbx:uniqueme}
\DeclareEntryOption{uniqueme}[true]{\csuse{bool#1}{cbx:uniqueme}}

\newbibmacro*{uniqueshorthand}{%
\ifbool{cbx:uniqueme}{\addspace%
    \printtext[brackets]{%
    	\ifnameundef{translator}
    	{\ifnameundef{intranslator}%
        	{\iffieldundef{series}%
      	{\printnames[name:family]{editor}}%
     	{\usebibmacro*{series}}}%
        {\printnames[name:family]{intranslator}}}%
    	{\printnames[name:family]{translator}}}%
  }%
{}%
}

\renewbibmacro*{cite:shorthand}{%
  \ifbool{cbx:seenote}%
  {\printtext{\printfield{shorthand}}}%
  {\printtext[bibhyperref]{\printfield{shorthand}%
    \usebibmacro*{uniqueshorthand}}%
  }%
}
```
Damit kann man den Einträgen die Option `uniqueme` zuweisen, die man erweitert haben möchte. Es gibt bei antiken Werken i.d.R. immer eine Standardausgabe, diese bekommt dann nur `options={ancient}`, hat man hingegen weitere Ausgaben desgleichen Werks kann man `options={ancient,uniqueme}` setzen und bekommt für die weiteren Ausgaben jeweils den `translator`/ `intranslator` oder `series` mit angezeigt.

**Comment by LukasCBossert** [comment]
Jetzt muss nur noch die Sortierreihenfolge angepasst werden: Zuerst die `shorthand` ohne Erweiterung, dann die mit Erweiterung in alphabetischer Reihenfolge.

**Comment by LukasCBossert** [comment]
wurde in Version 2.2 mit der Option `cbx:uniqueme` gelöst.
