### ISSUE TITLE
TeX-Dokumentations-Datei für Bibliographiestil 'archaeologie'

### ISSUE THREAD

**Issue by giovannotti** [LukasCBossert/biblatex-archaeologie#4]
Das Verfassen der Dokumentations-TeX-File würde uns helfen, Fehl-, Schwachstellen und Bugs ausfindig zu machen. Ich habe zum Beispiel nicht mehr genügend Überblick.

**Comment by LukasCBossert** [comment]
Das stimmt. geht mir bei meinen eigenen Sachen auch schon teilweise so.
ICh werde mich zwingen mehr/alles in die readme-datei zu schreiben.


Am 26.06.2015 um 15:03 schrieb Johannes <notifications@github.com>:

Das Verfassen der Dokumentations-TeX-File würde uns helfen, Fehl-, Schwachstellen und Bugs ausfindig zu machen. Ich habe zum Beispiel nicht mehr genügend Überblick.

**Comment by LukasCBossert** [comment]
Datei „archaeologie.tex“ wurde angelegt. (voll lauffähig - siehe archaeologie.pdf)
Darin kann man die Beispiele, macros, Umgebungen, etc. beschreiben. 


Am 26.06.2015 um 15:03 schrieb Johannes <notifications@github.com>:

Das Verfassen der Dokumentations-TeX-File würde uns helfen, Fehl-, Schwachstellen und Bugs ausfindig zu machen. Ich habe zum Beispiel nicht mehr genügend Überblick.

**Comment by LukasCBossert** [comment]
Die ersten Beschreibungen sind in "archaeologie.tex" eingetragen.
Doppelt Kommentiertes muss von geschichtsfrkl auf archaeologie sukzessive angepasst werden.

**Comment by LukasCBossert** [comment]
Soweit abgeschlossen.

Jetzt geht es um "Verständlichkeit" und "Vollständigkeit".
