### ISSUE TITLE
Initialen-Steuerung

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#57]
Soweit ich gelesen habe, sollte man die Angabe der Initialen steuern können:
```
  Author                   = {Hufschmid, {Th}omas},
```
müsste dann 

```
Th. Hufschmid
```
draus werden. Aber es klappt nicht!?

**Comment by LukasCBossert** [comment]
ok, habs gefunden:
http://tex.stackexchange.com/questions/227938/two-letter-initials-in-bibliography

`{\relax Th}eo`

**Comment by moewew** [comment]
Mit Biber kann man auch einiges automatisieren http://tex.stackexchange.com/q/297489/ (oder http://tex.stackexchange.com/q/295476/) insbesondere zusammen mit http://tex.stackexchange.com/q/297336/

**Comment by LukasCBossert** [comment]
wenn ich die von http://tex.stackexchange.com/a/295486/98739      vorgeschlagene Lösung einbaue,
ändert sich nichts in der Ausgabe?!

s. commit

**Comment by moewew** [comment]
Es sollte sich doch auch nichts ändern? Die Idee ist doch nur, dass man es sich selbst sparen kann, in der `.bib`-Datei das `{\relax ...}` zu setzen, da das jetzt automatisch gemacht wird. Ich gebe aber zu, dass solche automatischen Lösungen immer auch Probleme verursachen können und man so eine Funktion vielleicht nur optional anbieten sollte.

**Comment by LukasCBossert** [comment]
Wenn das `{\relax ... }` automatisch gesetzt wird ist es in der Bibliographie aber nicht sichtbar.
Da sehe ich bei den Einträgen

```
@Review{Hufschmid_2010,
  Title                    = {Von Caesars \emph{theatron kynegetikon} zum \emph{amphitheatrum novum} Vespasians},
   related = {Welch_2007},
     relatedtype= {reviewof},
  Author                   = {Hufschmid, Thomas},
  Pages                    = {487--504},
  Volume                   = {23},
  Year                     = {2010},
  Journaltitle             = JRA-lang,
  Shortjournal             = JRA-kurz,
}


@Book{Mann_2011,
  Title                    = {\enquote{Um keinen Kranz, um das Leben kämpfen wir!}},
  Author                   = {Mann, Christian},
  Location                 = {Berlin},
  Number                   = {14},
  Publisher                = {Verlag Antike},
  Series                   = {Studien zur Alten Geschichte},
  Subtitle                 = {Gladiatoren im Osten des Römischen Reiches und die Frage der Romanisierung},
  Year                     = {2011},
}
```

<img width="737" alt="screen shot 2016-03-16 at 14 15 16" src="https://cloud.githubusercontent.com/assets/12896078/13813387/917e501e-eb81-11e5-86f8-f07b3dea3560.png">
<img width="731" alt="screen shot 2016-03-16 at 14 15 21" src="https://cloud.githubusercontent.com/assets/12896078/13813388/9218aea2-eb81-11e5-95d2-6c044fc805df.png">

Wobei dich dachte, dass dann stünde "Th. Hufschmid" und "Chr. Mann" ?

**Comment by moewew** [comment]
Mhh, bei mir funktioniert es ganz prima.

**Comment by LukasCBossert** [comment]
Dann ist es umso merkwürdiger.

**Comment by LukasCBossert** [comment]
![screen shot 2016-03-16 at 15 13 59](https://cloud.githubusercontent.com/assets/12896078/13815156/bc8e31d6-eb89-11e5-8b64-3553c4f71130.png)
Beim MWE funktioniert es, nicht aber bei der `archaeologie.tex`!?

**Comment by LukasCBossert** [comment]
Das Steuern über eine Präambel-Option (`initials`) schlägt fehl:


```
\newbool{bbx:initials}%
\DeclareBibliographyOption{initials}[true]{\csuse{bool#1}{bbx:initials}}

\ifbool{bbx:initials}{%
\DeclareStyleSourcemap{%%		%http://tex.stackexchange.com/a/295486/98739     
  \maps[datatype=bibtex]{%
    \map{%
        % Author field
      \step[fieldsource=author,%
        match={\regexp{\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))(\S*,)}},%
        replace={\regexp{\{$1\}$3}}]% Protect last names (first last)
      \step[fieldsource=author,%
        match={\regexp{([^,]\s)\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))}},%
        replace={\regexp{$1\{$2\}}}]% Protect last names (last, first)
      \step[fieldsource=author,%
        match={\regexp{\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))([^\}])}},%
        replace={\regexp{\{\\relax\{\}$1\}$3}}]% Insert \relax after abbreviating
      % Editor field
      \step[fieldsource=editor,%
        match={\regexp{\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))(\S*,)}},%
        replace={\regexp{\{$1\}$3}}]% Protect last names (first last)
      \step[fieldsource=editor,%
        match={\regexp{([^,]\s)\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))}},%
        replace={\regexp{$1\{$2\}}}]% Protect last names (last, first)
      \step[fieldsource=editor,%
        match={\regexp{\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))([^\}])}},%
        replace={\regexp{\{\\relax\{\}$1\}$3}}]% Insert \relax after abbreviating
}}}
}{}
```

siehe letzter commit https://github.com/giovannotti/biblatex-archaeologie/commit/1ee0e4d5787fe00e3ab9521b03b007a308fa3633

**Comment by moewew** [comment]
Vielleicht liegt es an der Auswertungsreihenfolge der Optionen, mit `\AtBeginDocument` geht es

```
\AtBeginDocument{%
\ifbool{bbx:initials}{\typeout{YAAASSS}%
\DeclareStyleSourcemap{%%       %http://tex.stackexchange.com/a/295486/98739     
  \maps[datatype=bibtex]{%
    \map{%
        % Author field
      \step[fieldsource=author,%
        match={\regexp{\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))(\S*,)}},%
        replace={\regexp{\{$1\}$3}}]% Protect last names (first last)
      \step[fieldsource=author,%
        match={\regexp{([^,]\s)\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))}},%
        replace={\regexp{$1\{$2\}}}]% Protect last names (last, first)
      \step[fieldsource=author,%
        match={\regexp{\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))([^\}])}},%
        replace={\regexp{\{\\relax\{\}$1\}$3}}]% Insert \relax after abbreviating
      % Editor field
      \step[fieldsource=editor,%
        match={\regexp{\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))(\S*,)}},%
        replace={\regexp{\{$1\}$3}}]% Protect last names (first last)
      \step[fieldsource=editor,%
        match={\regexp{([^,]\s)\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))}},%
        replace={\regexp{$1\{$2\}}}]% Protect last names (last, first)
      \step[fieldsource=editor,%
        match={\regexp{\b(Chr|Ch|Th|Ph|[B-DF-HJ-NP-TV-XZ](l|r))([^\}])}},%
        replace={\regexp{\{\\relax\{\}$1\}$3}}]% Insert \relax after abbreviating
}}}
}{\typeout{NOOOO}}
}
```

aber das müsste man noch ein bisschen weiter untersuchen.

**Comment by LukasCBossert** [comment]
so funktioniert es.

Aber warum `\typeout{YAAASSS}%` und `\typeout{NOOOO}`?

**Comment by moewew** [comment]
Das brauchte ich nur um zu sehen, ob das Problem an der `\DeclareStyleSourcemap` oder am `\ifbool` lag.

**Comment by LukasCBossert** [comment]
Funktion ist erstmal als Easter-Egg eingebaut. Aktivierung über ``initials=true`` in der Präambel.
