### ISSUE TITLE
related-Funktion bei Übersetzungen

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#63]
Ich bin immer mehr von der `related`-Funktion begeistert.
Damit lassen sich ja auch wunderbar Originalausgaben und deren Übersetzungen verknüpfen:

```
@Book{Zanker_2013,
  Title                    = {La città romana},
  Author                   = {Zanker, Paul},
  Location                 = {Roma-Bari},
  Publisher                = {GLF},
  Series                   = {Storia della città},
  Year                     = {2013},
  language = {italian},
    Relatedtype              = {bytranslator},
  Related                  = {Zanker_2014},
  Translator               = {Senatore, Anna Maria}
}
@Book{Zanker_2014,
  Title                    = {Die römische Stadt},
  Author                   = {Zanker, Paul},
  Location                 = {München},
  Publisher                = {CHB},
  Subtitle                 = {Eine kurze Geschichte},
  Year                     = {2014},
  language = {german},
}
```

Diese Ausgabe ist noch etwas unbefriedigend:

```
P. Zanker, La città romana, Storia della città (Roma-Bari 2013), übers. von Die römische Stadt. Eine kurze Geschichte (München: CHB, 2014)

P. Zanker, Die römische Stadt. Eine kurze Geschichte (München 2014)
```

Es fehlt die Angabe `translator`(was funktioniert, wenn man die Relation umdreht: Zanker_2014 als Übersetzung von Zanker_2013), `publisher`und `location`ist nicht in der gewünschten Form und Option (mit und ohne `publisher`)

**Comment by moewew** [comment]
Das relevante Makro `related:bytranslator` ist in `biblatex.def` definiert. Dass wir hier den `translator` nicht sehen, könnte daran liegen, dass ich den in https://github.com/giovannotti/biblatex-archaeologie/issues/47 weggelöscht habe, würde ich tippen. Es gibt auch den `relatedtype` `translationof`.

**Comment by LukasCBossert** [comment]
Hm. Mit `translationof`passiert momentan noch nichts:

```
P. Zanker, La città romana, Storia della città (Roma-Bari 2013), Die römische Stadt. Eine kurze Geschichte (München 2014)
```

**Comment by moewew** [comment]
Ja `translationof` sollte eigentlich zum default zurückfallen. Wie soll es denn aussehen? Du musst das höchstwahrscheinlich mit
```
\newbibmacro*{related:translationof}[1]{...}
```
selbst basteln.

**Comment by LukasCBossert** [comment]
Mir schwebt etwas vor in der Art von 
```
P. Zanker, La città romana, Storia della città (Roma-Bari 2013), aus dem Deutschen übers. von A. M. Senatore,  *Die römische Stadt. Eine kurze Geschichte* (München 2014)
```

Das Makro heißt bei mir:

```
\newbibmacro*{related:translationof}[1]{%
  \entrydata{#1}{%
    \renewbibmacro*{name:hook}[1]{%
      \ifnumequal{\value{listcount}}{1}
        {\begingroup
         \mkrelatedstring%
         \lbx@initnamehook{#1}%
         \endgroup}
        {}}%
    \usebibmacro{translation}%
    \printtext[emph]{\usebibmacro{title}}%
    \setunit{\addspace}%
\usebibmacro{location+edition+year}%
      }}
```
Aber ich verstehe nicht warum `\usebibmacro{translation}` nicht funktioniert, bzw. nichts davon angezeigt wird.

Gibt es eine Möglichkeit dass diese `related`-Einträge von  der Option `uebersetzung` ausgenommen werden? Ansonsten steht zweimal `translator`und der Originaltitle (einmal als `origtitle`und einmal über `related`) da.

**Comment by moewew** [comment]
Möglicherweise müssen wir mein `AtEveryBibitem` aus https://github.com/giovannotti/biblatex-archaeologie/issues/47 noch einmal überdenken.

Das ist hier aber tatsächlich gar nicht das Hauptproblem. Um das tolle Feature zu ermöglichen, dass Herausgeber und Übersetzer zusammenfallen können ("herausgegeben und übersetzt von"), muss `biblatex` den `translator` löschen (mit `\clearname{translator}`), wenn Du ihn dann brauchst, ist er nicht mehr da.

Außerdem greifst Du in `\entrydata{#1}{...}` mit `translator` auf den `translator` des verlinkten Eintrages zu, aber der hat hier gar keinen. Das könnte man mit `\entrydata*` retten, denn dann werden die Felder des parents auch gespeichert und als `saved...` verfügbar gemacht.

```
\newbibmacro*{related:translationof}[1]{%
  \entrydata*{#1}{%
    \renewbibmacro*{name:hook}[1]{%
      \ifnumequal{\value{listcount}}{1}
        {\begingroup
         \mkrelatedstring%
         \lbx@initnamehook{#1}%
         \endgroup}
        {}}%
    \printnames{savedtranslator}%
    \printtext[emph]{\usebibmacro{title}}%
    \setunit{\addspace}%
\usebibmacro{location+edition+year}%
}}
``` 

würde funktionieren, wenn wir nicht das `\clearname{translator}` hätten.

**Comment by LukasCBossert** [comment]
Auch wenn `clearname{translator}`auskommentiert wird, wird der Übersetzer an der "falschen" Stelle gesetzt:
```
P. Zanker, La città romana, übers. von A. M. Senatore, Storia della città (Roma-Bari 2013), Übers. von Die römische Stadt. Eine kurze Geschichte (München 2014)
```

**Comment by moewew** [comment]
Ja, es wird nämlich immer noch ein `\clearname{translator}` von `byeditor+others` in `\usebibmacro{translation}` ausgelöst. Das können wir wohl  nur ändern, wenn da noch Abfragen kommen, die testen, ob wir `byeditor+others` aufrufen dürfen. 


Vielleicht sollte die ganze Sache nochmal genauer durchdacht werden. Ich fand meine Ideen mit dem kurzen Code, der auf möglichst viel Standardmakros zurückgreift, zwar ganz nett, aber es hat eben auch Nachteile.

**Comment by LukasCBossert** [comment]
Soweit ich das sehe, tritt das Problem nur bei der `related`-Funktion mit `relatedtype={translationof}`auf  - das scheint mir nicht prioritär zu sein, sodass ich das Problem erstmal auf Version 2.0 verschiebe.
Die Angabe und Verknüpfung funktioniert, es ist eben noch nicht *ganz* schön, aber durchaus schon brauchbar.

**Comment by LukasCBossert** [comment]
Wie könnte deine obige Idee mit der extra Abfrage gestaltet werden @moewew ?

Wenn ich das richtige sehe müsste man an zwei Stellen ansetzen:

```
\renewbibmacro{bytranslator+others}{%
  \ifnameundef{translator}
    {}
    {\usebibmacro{bytranslator+othersstrg}%
     \setunit{\addspace}%
     \printnames[bytranslator]{translator}%
     \iffieldequals{relatedtype}{translationof}%
                    {}{\clearname{translator}}%
     \newunit}%
 % \usebibmacro{with others}
  }
%%(aus der `biblatex_.def`)


\newbibmacro*{related:translationof}[1]{%
  \entrydata*{#1}{%
    \renewbibmacro*{name:hook}[1]{%
      \ifnumequal{\value{listcount}}{1}
        {\begingroup
         \mkrelatedstring%
         \lbx@initnamehook{#1}%
         \endgroup}
        {}}%
	\setunit*{\addspace\bibstring{origpubas}\space}% nicht verwendet?!
    \printtext[emph]{\usebibmacro{title}}%
    \setunit{\addspace}%
    \bibstring{bytranslator}%keine Sprache ausgegeben?!
    \setunit{\addspace}%
    \printnames{savedtranslator}%
\usebibmacro{location+edition+year}%
}}
```


und 
```
\AtEveryBibitem{%
  	\ifboolexpr{bool {bbx:translation}%
  					 or bool {cbx:ancient}%
  					 or bool {cbx:frgancient}}%
    	{}%
    	{\iffieldequals{relatedtype}{translationof}% Abfrage (kann die in die \ifboolexpr integriert werden?)
              {\clearname{translator}%
    			\clearfield{origtitle}%
		       }%
}
}
```

Die Bibeinträge
```
@Book{Zanker_2013,
  Title                    = {La città romana},
  Author                   = {Zanker, Paul},
  Location                 = {Roma-Bari},
  Publisher                = {GLF},
  Series                   = {Storia della città},
  Year                     = {2013},
  language = {Italian},
    Relatedtype              = {translationof},
  Related                  = {Zanker_2014},
  Translator               = {Senatore, Anna Maria}
}
@Book{Zanker_2014,
  Title                    = {Die römische Stadt},
  Author                   = {Zanker, Paul},
  Location                 = Munich,
    Publisher                = {CHB},
  Subtitle                 = {Eine kurze Geschichte},
  Year                     = {2014},
  language = {German},
}
```

Allerdings gibt es eine Fehlermeldung, die ich nicht lokalisieren kann:
`! Argument of \@secondoftwo has an extra }.`

Das Ergebnis sieht momentan so aus:

<img width="865" alt="bildschirmfoto 2016-05-28 um 17 16 25" src="https://cloud.githubusercontent.com/assets/12896078/15628075/fe57c792-24f7-11e6-8cf8-ba6f3f8e404f.png">

**Comment by moewew** [comment]
Ich bin gerade nicht so drin in der Materie, aber `\iffieldequals` sollte hier wohl besser `\iffieldequalstr` sein, wenn Du mit dem Inhalt "translationof" vergleichen möchtest. (Siehe auch http://tex.stackexchange.com/a/290935/)

In der Tat kann man ein `\iffieldequalstr` auch in `\ifboolexpr` einbauen:
```
\ifboolexpr{test {\iffieldequalstr{pubstate}{under review}}}
```
sollte gehen.

**Comment by LukasCBossert** [comment]
Vielen Dank. mit `\iffieldequalstr`kommt es jetzt zu keiner Fehlermeldung mehr. Aber irgendetwas löscht wohl noch immer den `translator`.

**Comment by moewew** [comment]
Eine Suche in `biblates.def` nach `\clearname{translator}` fördert einige Fundstellen zutage. Die müssten alle untersucht werden, ob sie aufgerufen werden und dann gegebenenenfalls modifiziert werden. Das ist natürlich besonders bei `editor+othersstrg` ein furchtbares Gefrickel in den Innereien von `biblatex`. Vielleicht gibt es noch eine bessere Idee. 

... Zum Beispiel: Ihr überprüft am Anfang (`begentry` oder so), ob wir ein `translationof` haben. Wenn ja, speichert ihr den `translator ` mit `\savename` in ein temporäres Makro und löscht ihn dann. Erst im `related`-Teil stellt ihr ihn dann wieder her (mit `\restorename` - wenn das überhaupt nötig ist).

**Comment by moewew** [comment]
Ich habe mal eben ein bisschen gebastelt. Den Ansatz habe ich in obigem Pull-Request (#87) gepackt. Vielleicht ist das ja was.

**Comment by LukasCBossert** [comment]
Obwohl die verschiedene Sprachen für die Bibliographie übernommen werden, gilt dies für `bibstrings` nur teilweise:

<img width="631" alt="bildschirmfoto 2016-06-05 um 16 32 39" src="https://cloud.githubusercontent.com/assets/12896078/15806079/687fd828-2b3b-11e6-84db-de6c66a67a9f.png">

In allen Sprachen taucht das `trans. of` auf, obwohl dann eine andere Sprache ausgegeben werden soll (wie es bei bspw. `übers. von` funktioniert).

Mir ist unklar an welcher Stelle die Sprache innerhalb des Eintrags gewechselt wird -- oder warum das eine entsprechend angezeigt wird und das andere weiterhin auf Englisch stehen bleibt.
```
%-----------------------
\newbibmacro*{related:translationof}[1]{%
	\entrydata*{#1}{%
   	\restorename{savedtranslator}{\savedrelatedtranslator}%
    \printtext[emph]{\usebibmacro{title}}%
    \usebibmacro{location+edition+year}%
    	\newunit
    \bibstring{bytranslator}%keine Sprache ausgegeben?    
    	\setunit{\addspace}%
    \printnames{savedtranslator}
  	}
}
```

**Comment by LukasCBossert** [comment]
Ist wohl mittlerweile gelöst - in der aktuellen Dokumentation stimmt alles.
