### ISSUE TITLE
english documentation / Kurzdokumentation (deu)

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#84]
Hauptdokumentation in Englisch.

Kurze Einführungen (Übersicht über Optionen in Englisch und Deutsch).

**Comment by LukasCBossert** [comment]
Man könnte bei der Kurzanleitung eine Bibliographie anfügen, die jeden Fall (Artikel, Buch, Sammelband,etc) aufzeigt.

**Comment by LukasCBossert** [comment]
Ist die `archaeologie-ger.tex` von deiner Seite aus fertig?

**Comment by giovannotti** [comment]
Was hältst du davon die beiden globalen Optionen ancient und corpora z.B. bibancient und bibcorpora zu nennen? Dann wären sie parallel zu lstpublishers etc. konstruiert und zusätzlich ist die Verwechslungsgefahr mit den Entry-Options-Einträgen ancient und corpora nicht so groß. Oder spricht was dagegen?

**Comment by LukasCBossert** [comment]
sehr gut. so habe ich mir das auch schon überlegt gehabt, war mir aber unsicher. änderst du es?

**Comment by giovannotti** [comment]
Ich hoffe, ich hab keine Stelle zu ändern vergessen...
4afb4534c7d8711ebbd4c0aed23910e5c5f5b1e4

**Comment by LukasCBossert** [comment]
man könnte auch die Bibliographie-Dateien auch umändern. --> archaeologie-bibancient.bib etc. ist zwar nicht zwingend notwendig, würde aber eine Einheitlichkeit mit der Option liefern.
