### ISSUE TITLE
@string bei journaltitle: long/short

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#88]
Es reicht aus, wenn man bspw. im Bibliographieeintrag schreibt:
```
journaltitle = RM,
shortjournal = RM-short,
```

anstatt wie bisher:
```
journaltitle = RM-long,
shortjournal = RM-short,
```

Das heißt, dass das `-long` wegfällt, sodass man sich etwas unnötige Tipparbeit spart und es ggf. intuitiver ist, dass der Eintrag bei `shortjournal` auch ein `-short` enthält, und bei `journaltitle` kein extra `-long` mehr, sondern nur der Standard, der eben keines notwendiges spezifizierendes Kürzel bedarf.

**Comment by giovannotti** [comment]
👍🏻 von mir dazu. viel intuitiver.

**Comment by LukasCBossert** [comment]
Ok, ich werde es entsprechend ändern.
