### ISSUE TITLE
list of publishers

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#90]
Neben der Liste mit den Städten kann man auch noch eine Liste mit den gängigen Verlagen anbieten --> `archaeologie-lstpublishers`, die mit `bbx:lstpublishers` geladen werden kann (noch nicht angelegt).

**Comment by LukasCBossert** [comment]
ok - ist in der `bbx` drin - muss noch in der `archaeologie-ger` eingetragen werden und eine Liste für `archaeologie.tex` (section 11) erstellt werden.

**Comment by LukasCBossert** [comment]
dann können die , teilweise schon genutzten, Felder `publisher` mit den `@strings` versehen werden.

**Comment by giovannotti** [comment]
In der `archaeologie-ger` ist es drin.
Siehe b65253255a74dc9068fbc632de4d8088c0ae3b05 und 3e3c27516fcadb2cc47615190d0b45f8bf343abe. Hoffe, das passt.
