### ISSUE TITLE
nur bei uniquename - Nachname, Vornameninitial

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#91]
@moewew : Aufbauend auf der Lösung präsentiert bei http://tex.stackexchange.com/a/126178/98739
habe ich folgendes versucht, indem ich aus dem dort vorgeschlagenen

```
\DeclareNameAlias{sortname}{last-first}
\DeclareNameFormat{labelname}{%
  \ifcase\value{uniquename}%
    \usebibmacro{name:last}{#1}{#3}{#5}{#7}%
  \or
    \ifuseprefix
      {\usebibmacro{name:last-first}{#1}{#4}{#5}{#8}}
      {\usebibmacro{name:last-first}{#1}{#4}{#6}{#8}}%
  \or
    \usebibmacro{name:last-first}{#1}{#3}{#5}{#7}%
  \fi
  \usebibmacro{name:and others}}
```

das gebastelt habe:
```
\DeclareNameFormat{labelname}{%
  \ifcase\value{uniquename}%
    {\usebibmacro{name:family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
   \or
    \ifuseprefix
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefix}
          {\namepartsuffixi}%
    \usebibmacro{name:andothers}}
  \or
    {\usebibmacro{name:family-given}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefix}
          {\namepartsuffixi}%
    \usebibmacro{name:andothers}}
  \fi
  \usebibmacro{name:and others}}
```

Aber leider wird der uneindeutige Name nun gar nicht mehr angegeben.

**Comment by moewew** [comment]
Bevor Du an `labelname` rumbastelst, schau doch erstmal, ob Dir der Standard in `biblatex` gefällt. Der ist
```
\DeclareNameFormat{labelname}{%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
    \usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:andothers}}
```

Wenn der in eurem Stil nicht verändert wird, sollte der sofort verfügbar sein, wenn die `uniquename`-Option aktiviert wird. Davon ausgehend kannst Du dann Änderungen vornehmen. Ich gehe davon aus, dass es mit Deinem Code oben Probleme gibt, da ein Branch der `\ifuseprefix`-Anweisung fehlt. Außerdem taucht nun `\usebibmacro{name:and others}` (richtig ohne Leerzeichen `\usebibmacro{name:andothers}`) viel zu häufig auf.

**Comment by LukasCBossert** [comment]
ah - das ist viel besser als den alten Code anpassen zu wollen.

```
\DeclareNameFormat{labelname}{%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:family-given} %<<<<<<<
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:family-given} %<<<<<<<
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
    \usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:andothers}}
```

Wenn ich die zwei `bibmacros` von `{name:given-family}` zu `{name:family-given}` tausche, dann scheint es zu klappen:
> Müller, A. 2015
> Müller, B. 2015

ich weiß aber nicht, ob ich dort sonst noch was einstellen muss?

**Comment by moewew** [comment]
Ich würde dann im letzten Teil auch `\usebibmacro{name:family-given}` statt `\usebibmacro{name:given-family}` für "Müller, Anne" statt "Anne Müller" schreiben. Das ist für den Fall, dass ein Initial nicht ausreicht, um Autoren zu unterscheiden. (Wenn Du Anton Müller und Anne Müller hast, bekommst Du dann "Müller, Anton" und "Müller, Anne", denn "Müller, A." alleine ist nicht mehr eindeutig.)

**Comment by LukasCBossert** [comment]
ah, genau an den Fall habe ich auch schon gedacht und mich gefragt, wie das gelöst wird.

--- gesendet von unterwegs ---

**Comment by LukasCBossert** [comment]
Also mit 
```
\DeclareNameFormat{labelname}{%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:family-given}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:family-given}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
   	\usebibmacro{name:family-given}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:and others}}
```
und `uniquename=minfull` werden die Vornamen von Nachnamensgleichen Autoren nicht ausgeschrieben, sondern es wird auf das "a/b-System" (2015a bzw. 2015b) umgestellt (nicht jedoch für unterschiedliche Vornamen).

**Comment by moewew** [comment]
Ah ja natürlich. Wenn die Option `giveninits` (the option formerly known as `firstinits`) aktiviert ist, dann kannst Du ganze Vornamen vergessen. Du solltest auch eine Warnung bekommen, dass die `uniquename`-Einstellung nicht passt.

Du kannst Dir jetzt überlegen, ob Du `giveninits` weglassen möchtest und dann unter Umständen einige Namensformate anpassen musst, um im Allgemeinen Initialen zu verwenden. Oder ob es Dir um den letzten Schritt im `uniquename`-Prozess nicht so schade ist.

**Comment by LukasCBossert** [comment]
Aha, wenn ich `giveninits` abschalte, dann klappt alles. Wenn ich das richtig sehe, brauchen wir auch `giveninits` auch gar nicht (mehr). Ich sehe auch sonst kein Namenformat, bei dem `giveninits` zum Tragen kommen würde.

**Comment by LukasCBossert** [comment]
Ich habe entdeckt, wo `givenintis` doch noch relevant ist: In der Bibliographie werden jetzt alle Vornamen ausgeschrieben. Diese sollen jedoch nur mit dem Initial angegeben werden und bei Bedarf mit der Option `bibfullname`

```
\DeclareBibliographyOption{bibfullname}[true]{%
			\ExecuteBibliographyOptions{giveninits=false}}
```
voll ausgeschrieben werden.

Das Namenformat wurde an sich schon definiert:
```
\DeclareNameFormat{name:inreference}{%
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
    \usebibmacro{name:and others}}
``` 
Müsste also "nur" als Standard geladen werden????

**Comment by moewew** [comment]
Wenn Du "in der Bibliographie" schreibts, meinst Du dann alle Namen in der Bibliographie oder nur bestimmte? Was ist z.B. mit denjenigen Namen die wegen uniquename ganz ausgeschrieben wurden?

Wahrscheinlich musst Du an den Formaten `default` und `sortname` rumschrauben. Je nach Wünschen, gibt es auch noch viele andere Formate, siehe ab Zeile 850 in `biblatex.def`.

**Comment by LukasCBossert** [comment]
Aktuell werden die Namen der Autoren/Herausgeber/Übersetzer ausgeschrieben, nicht die Namen in den Labels. Beim Label werden nur die Namen ausgeschrieben, die wegen `uniquename` ausgeschrieben werden. 

Wie es aktuell ist, würde dies der Option `bibfullname` entsprechen - soll aber nicht der Standard sein. 

Ich schaue mal in der `biblatex.def` ob ich da eine Lösung finde.

**Comment by LukasCBossert** [comment]
Wenn ich setze
```
\DeclareNameAlias{author}{name:interference} %in der cbx definiert
	\DeclareNameAlias{editor}{author}
	\DeclareNameAlias{translator}{author}
```
passt alles.

Aber sobald ich die Option `bibfullname` einbauen will, ändert sich nichts:

```
\newbool{bbx:bibfullname}
\DeclareBibliographyOption{bibfullname}[true]{\csuse{bool#1}{bbx:bibfullname}}

\DeclareNameAlias{author}{\ifbool{bbx:bibfullname}{given-family}{name:inreference}}
	\DeclareNameAlias{editor}{author}
	\DeclareNameAlias{translator}{author}
```

Es scheint so, als würde `bibfullname` gar nicht berücksichtigt werden.

**Comment by LukasCBossert** [comment]
Heureka! 

```
\DeclareBibliographyOption{bibfullname}[true]{\csuse{bool#1}{bbx:bibfullname}
			\DeclareNameAlias{author}{given-family}}

...

\DeclareNameFormat{name:default}{%
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
    	{\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
    \usebibmacro{name:andothers}}
    
\DeclareNameAlias{author}{name:default}
\DeclareNameAlias{editor}{author}
\DeclareNameAlias{translator}{author}
```

Jetzt kann man mit `bibfullname` den vollen Namen anzeigen lassen.

**Comment by LukasCBossert** [comment]
Wie kann bei den Namensformaten `\def\cbx@arch@citeauthorformat@family{%` etc. die `uniquenames` berücksichtigt werden?

Momentan wird bei `\citeauthor` nicht unterschieden, ob der Name uneindeutig ist.

**Comment by moewew** [comment]
Für `\cbx@arch@citeauthorformat@...` müssten wir dann das nachbauen, was in 

```
\DeclareNameFormat{labelname}{%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
    \usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:andothers}}
```

steht, aber so anpassen, dass es sinnvoll ist.

De Zähler `uniquename`, der hier abgefragt wird, hat drei mögliche Werte

- Er ist 0, wenn der Nachname ausreichend ist.
- Er ist 1, wenn ein Vornameninitial nötig ist, um den Namen eindeutig zu machen.
- Er ist 2, wenn der gesamte Name benötigt wird.


Je nach dem, wie die Option `citeauthorformat` sich dem `uniquename` unterordnen soll (oder umgekehrt), kannst Du dann Anpassungen ausführen.

Wenn z.B. `family` heißen soll "Nachname solange es geht und dann so viel Info wie nötig für Eindeutigkeit", dann wäre schon 

```
\def\cbx@arch@citeauthorformat@family{%
  \DeclareNameAlias{citeauthor}{labelname}}
```
genug

für `initials` (was dann "Initialen, außer wir brauchen den ganzen Namen" heißt), brauchen wir dann
```
\def\cbx@arch@citeauthorformat@initials{%
  \DeclareNameFormat{citeauthor}{%
    \ifnum\value{uniquename}=2%
      \usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiven}
        {\namepartprefix}
        {\namepartsuffix}%
    \else
      \ifuseprefix
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefix}
          {\namepartsuffixi}}
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefixi}
          {\namepartsuffixi}}%
    \fi
    \usebibmacro{name:andothers}}}
```

Der `\def\cbx@arch@citeauthorformat@firstfull` code müsste dann in seiner `\cbx@ifnameseen{\thefield{hash}}` Branch den passenden Code für entweder initials oder full beinhalten.

**Comment by LukasCBossert** [comment]
Perfekt! Vielen Dank!

Ich habe deinen Vorschlag etwas angepasst, sodass bspw. bei Option `family` die Initialen vor dem Nachnamen stehen, da `\citeauthor` ja im Fließtext aufgerufen wird, ist es angenehmer die Initialen vorgestellt zu haben. 
Dafür habe ich ein neues Namenformat erstellt:
```
  \DeclareNameFormat{name:family}{%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
   	\usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:and others}}


\def\cbx@arch@citeauthorformat@family{%
  \DeclareNameAlias{citeauthor}{name:family}}
```

Ähnliches auch für `initials`:

```
 \DeclareNameFormat{name:initials}{%
    \ifnum\value{uniquename}=2%
      \usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiven}
        {\namepartprefix}
        {\namepartsuffix}%
    \else
      \ifuseprefix
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefix}
          {\namepartsuffixi}}
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefixi}
          {\namepartsuffixi}}%
    \fi
    \usebibmacro{name:and others}}

\def\cbx@arch@citeauthorformat@initials{%
   \DeclareNameAlias{citeauthor}{name:initials}}
```

Bei `firstfull` habe ich einen Teil aus `initials` an entsprechender eingefügt, da es ja nur für den Fall der Uneindeutigkeit beim Nachnamen und Initial gelten muss:
```
\def\cbx@arch@citeauthorformat@firstfull{%
  \DeclareNameFormat{citeauthor}{%
    \cbx@ifnameseen{\thefield{hash}}
      {\ifnum\value{uniquename}=2%
      \usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiven}
        {\namepartprefix}
        {\namepartsuffix}%
    \else
    \ifuseprefix
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefix}
          {\namepartsuffixi}}
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefixi}
          {\namepartsuffixi}}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiven}
        {\namepartprefix}
        {\namepartsuffix}%
       \cbx@nameseen{\thefield{hash}}}%
    \usebibmacro{name:andothers}}}
```
Soweit ich sehe, passt alles. 
Ich konnte dadurch auch das bisheriger Format `name:default` durch `name:initials` ersetzen, da schließlich bei Uneindeutigkeit immer erweitert werden soll.

**Comment by moewew** [comment]
Vielleicht stehe ich gerade auf den Schlauch, aber Dein `name:family` unterscheidet sich doch gar nicht von dem standard `lablename`-Format, oder übersehe ich da was (passt der Stil `labelname` an)?

Beachte (ich glaube, bis jetzt macht es noch keinen Unterschied, aber behalte es im Auge), dass die `uniquename`-Information nur für den als `labelname` identifizierten Namen bereitgestellt werden. Wenn Du ein `@book` mit `author` und `editor` hast, dann sind die Informationen nur für `author` da. (Das könnte bei `@inreference`s problematisch werden.)

**Comment by LukasCBossert** [comment]
Bei `labelname` heißt es "Nachname, V.", aber für die `citeauthor`/`name:family` soll es im Bedarfsfall "V. Nachname" heißen (also Vor- und Nachname getauscht).

Aha, das ist mir nur bei einem Eintrag aufgefallen. Ich habe aber auch nur einen Eintrag mit `author` und `editor`.
![bildschirmfoto 2016-07-14 um 16 01 40](https://cloud.githubusercontent.com/assets/12896078/16842083/61ac23ac-49dc-11e6-91d7-3feaf0ca5147.png)

```
@Book{Neufert_2002,
  author       = {Neufert, Ernst},
  editor       = {Neufert, Peter and Neufert, Cornelius and Neff, Ludwig and Franken, Corinna},
  title        = {Bauentwurfslehre},
  subtitle     = {Grundlagen, Normen, Vorschriften über Anlage, Bau, Gestaltung, Raumbedarf, Raumbeziehungen, Maße für Gebäude, Räume, Einrichtungen, Geräte mit dem Menschen als Maß und Ziel},
  publisher    = {Vieweg},
  location     = {Wiesbaden},
  year         = {2002},
  edition      = {37},
  origlocation = {Berlin},
  origyear     = {1936},
}
```
Ist das (schnell) zu lösen?

**Comment by moewew** [comment]
OK, die Frage ist, ob das gewollt war, dass `labelname` "Müller, A." schreibt und nicht "A. Müller" (wenn in Zitaten mit `\cite` und Freunden der Name uneindeutig ist). Wenn ja, dann brauchst Du für `citeauthor` ein eigenes Format, wenn nein, dann kannst Du überall dasselbe verwenden.

Soweit ich weiß, gibt es keine Möglichkeit, `uniquename` für andere Namen zu bekommen, die nicht `labelname`s sind.

**Comment by LukasCBossert** [comment]
genau. es ist beabsichtigt, dass für `labelname` „Müller, A.“ kommt und für `\citeauthor` aber „A. Müller“. 
Da diese Vertauschung vom Vornamen gewünscht ist, passt es, dass dafür das eigene Format 
```
  \DeclareNameFormat{name:family}{%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
   	\usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:and others}}
```
angelegt ist.?

**Comment by moewew** [comment]
Wenn das so gewollt ist, dann brauchen wir mehere Formate. Wie das jetzt der Fall ist. Die Bezeichung `name:family` ist dann vielleicht ein bisschen irreführend, aber OK.

**Comment by LukasCBossert** [comment]
Ich habe zwei Formate definiert
```
\DeclareNameFormat{name:family}{%
  \ifcase\value{uniquename}%
    \usebibmacro{name:family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \or
    \ifuseprefix
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefix}
        {\namepartsuffixi}}
      {\usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiveni}
        {\namepartprefixi}
        {\namepartsuffixi}}%
  \or
   	\usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
  \fi
  \usebibmacro{name:andothers}}
  
 \DeclareNameFormat{name:initials}{%
    \ifnum\value{uniquename}=2%
      \usebibmacro{name:given-family}
        {\namepartfamily}
        {\namepartgiven}
        {\namepartprefix}
        {\namepartsuffix}%
    \else
      \ifuseprefix
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefix}
          {\namepartsuffixi}}
        {\usebibmacro{name:given-family}
          {\namepartfamily}
          {\namepartgiveni}
          {\namepartprefixi}
          {\namepartsuffixi}}%
    \fi
    \usebibmacro{name:and others}}
```
Und zwar für:
```
\def\cbx@arch@citeauthorformat@family{%
  \DeclareNameAlias{citeauthor}{name:family}}

\def\cbx@arch@citeauthorformat@initials{%
   \DeclareNameAlias{citeauthor}{name:initials}}
```

Reichen die nicht aus? Meine Idee bei der Namenswahl `name:family` war, dass erstmal nur `family` gesetzt wird und nur bei Bedarf um Initiale erweitert wird.

**Comment by moewew** [comment]
Zusammen mit `labelname` ist das genug. (Brauchen wir `\DeclareNameFormat{frg}` noch?)

Ich überlege nur, ob man
```
\def\cbx@arch@citeauthorformat@full{%
  \DeclareNameFormat{citeauthor}{%
    \usebibmacro{name:given-family}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}%
\usebibmacro{name:andothers}}}
```
zu
```
\def\cbx@arch@citeauthorformat@full{%
  \DeclareNameAlias{citeauthor}{given-family}}
```
verkürzen könnte.

**Comment by LukasCBossert** [comment]
Stimmt: 
```
\def\cbx@arch@citeauthorformat@full{%
  \DeclareNameAlias{citeauthor}{given-family}}
```
ist ausreichend. Denn es wird ja nicht auf Uneindeutigkeit unterschieden. 

Ja, `\DeclareNameFormat{frg}` kann auch raus, da es ersetzt werden kann, wie ich gerade getestet habe:
```
\newbibmacro*{cite:frgname}{%
      \ifnameundef{shorteditor}%
           {\printnames[name:family]{editor}}%
           {\printnames{shorteditor}}%
}
```
Es soll nur der Nachname in die `postnote` gesetzt werden, wenn der `shorteditor` nicht angegeben ist. 

Man kann aber sicherlich da etwas automatisieren:
Dass automatisch nur der/die ersten Buchstaben des Nachnamens eingesetzt werden. Dann spart man sich das manuelle Einsetzen in `shorteditor`?!

**Comment by LukasCBossert** [comment]
Ein 
```
\newbibmacro*{cite:frgname}{%
         \printnames[strwidth=1,strside=left]{editor}%
}
```
funktioniert natürlich nicht....

**Comment by moewew** [comment]
`strwidth=1,strside=left` und Konsorten sind nur für das AlphaTemplate der `alphabetic`-Stile nutzbar. `biblatex` bietet zur Zeit keine direkte Möglichkeit, Felder automatisch zu beschneiden.

Ich stehe einer automatischen Lösung skeptisch gegenüber. Woher weißt Du, wie viele Buchstaben nötig sind (sind es immer drei oder vier?), was machst Du, wenn die nicht ausreichen (Plinius, d. Ä. vs. Plinius d. J.)?
That said, kann ich mir vorstellen, dass mit dem sourcemap-Feature durchaus etwas gebastelt werden kann, das funktioniert, wenn es eine eindeutige Regel gibt (wie "nimm die ersten vier Buchstaben des Namens und pack einen Punkt dahinter"). Denn Sinn dieser Fingerübung würde ich dann allerdings bezweifeln.

**Comment by LukasCBossert** [comment]
Ok, dann lassen wir es lieber bei der manuellen Eingabe des einzelnen Buchstabens. (In diesem Fall [bei Fragment-Sammlungen] sollten nicht die antiken Autoren abgekürzt werden, sondern die Herausgeber der Fragment-Sammlungen). 
Damit scheint mir die Sache mit der Namensgebung (bis auf die Sache mit `author` bei gleichzeitigem `editor` gelöst zu sein – ist aber erstmal zu verkraften), sodass ich den Issue schließen kann.
