### ISSUE TITLE
subvoce

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#92]
Mir ist der Vorteil von einem `bibstring` mit `subvoce` nicht klar, da ja in allen Sprachen 
> s. v.
stünde, weil es sich um eine lateinische Bezeichnung handelt. Zumindest kenne ich kein sprachabhängiges Äquivalent. Oder ist mir was entgangen, @moewew ?

**Comment by moewew** [comment]
Ich spreche keine andere Sprache auf einem annähernd hohen Niveau, um das beurteilen zu können.

Trotzdem finde ich es sinnvoller, solche Strings mittels der `bibstring`-Funktion zu verwalten. Zum Einen werden (fast) alle Strings in `biblatex` so behandelt und es ist eine gute Angewohnheit, diesem Beispiel zu folgen; zum Zweiten könnte es ja sein, dass Sprachen mit anderen Alphabeten auch eigene Bezeichnungen haben und nicht das Lateinische verwenden. Der zusätzliche Aufwand wird sich in Grenzen halten und das Ergebnis ist eine uniforme Behandlung von direkt gedruckten Strings.

**Comment by LukasCBossert** [comment]
ok. Ich habe es so umgesetzt. Dann können zumindest die Sprachen Englisch, Deutsch, Italienisch, Französisch und Spanisch auf diesen `bibstring` zugreifen.
