### ISSUE TITLE
Code-Vereinfachungen

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#93]
An manchen Stellen scheint mir der Code etwas ›unschön‹ und umständlich. Sicherlich gibt es bessere Varianten dafür, @moewew ?

Ein Beispiel betrifft die Abfrage ob etwas dem `entrytype`  `inreference` entspricht UND gleichzeitig die Option `inreferences` aktiviert ist:
Aktuell wird es gelöst mit:
```
%cbx: Zeile 424 und 439
\ifboolexpr{%
		 test {\ifbool{bbx:inreferences}}%
		 and %
		 test	{\ifentrytype{inreference}}%
		 }%
		 {\printtext}%
		{\printtext[bibhyperref]}


```
Ebenso in der `cbx` Ziele 286:
```
\newbibmacro{cite}{%
	\ifboolexpr{%
		 test {\ifbool{bbx:inreferences}}%
		 and %
		 test {\ifentrytype{inreference}}%
		 }%
	{\usebibmacro{cite:lexikon}}
	{\ifbool{cbx:seenote}
		{\usebibmacro{cite:seenote}}
		{{\printtext[bibhyperref]{\iffieldundef{shorthand}%
    			{\ifnameundef{labelname}%
           		{\usebibmacro{cite:label}%
            			\setunit{\labelyeardelim}%
			}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
        \usebibmacro{cite:year}}%
        {\usebibmacro{cite:shorthand}}}}%
       }%
    }
```

**Comment by LukasCBossert** [comment]
So würde ich auch  `\printtext[parens]{\printnames[name:initials]{labelname}}% (`cbx`Zeile 611) vereinfachen wollen.
Aber mit `\DeclareFieldFormat[inreference]{labelname}{\mkbibparens{#1}}` klappt es nicht. 
Ich nehme an, dass es daran liegt, dass `labelname` ja kein `field` sondern ein `name` ist.
Aber ein `\DeclareNameFormat` ist ja was anderes?!

**Comment by moewew** [comment]
Die `\ifboolexpr`s aus dem ersten Beitrag finde ich eigentlich an sich sehr schön; man könnte eher konzeptionell darüber nachdenken, ob man den Code so restrukturieren sollte, dass sie nicht mehr nötig sind.

Bei der Geschichte mit `\DeclareFieldFormat[inreference]{labelname}{\mkbibparens{#1}}` ist Deine Anylse genau richtig. Theoretisch könntest Du ein eigenes Namensformat erstellen, da die Klammern einzuabauen würde aber einiges an Abfragen benötigen. Da würde ich dann eher bei `\printtext[parens]{\printnames[name:initials]{labelname}}` bleiben.

Was mir im Code auffällt, ist dass die Einrückung etwas inkonsitent wirkt. Die Übersichtlichkeit wird durch Einheitlichkeit in dieser Hinsicht enorm gesteigert. (Ich würde wie die Standarddateien grundsätzlich Einrückung im zwei Leerzeichen (kein Tabulator) pro Level vorschlagen.) (Siehe z.B. [`location+edition+year`](https://github.com/LukasCBossert/biblatex-archaeologie/blob/Beta-Version/archaeologie.bbx#L721))

In `booktitle+volume+editor` gibt es Aufrufe zu `\printnames[author][-\value{listtotal}]{editor}`, das scheint mir ein wenig merkwürdig. Grundsätzlich würe ich versuchen, bei `\print...`-Direktiven so wenig optionale Argumente wie möglich zu gebrauchen und alles über Optionen zu regeln.

Außerdem scheint es mir wieder sinnvoll, ein wenig auf die Suche nach ungenutzten Code (ungenutzten Optionen) zu gehen. Vielleicht lässt sich auch auf diese Art und Weise einiger Code verkürzen, indem man auf die Standards zurückgreift.

**Comment by LukasCBossert** [comment]
ok, wenn aus ›programmier-technischer‹ Sicht nichts gegen `\ifboolexpr` spricht, bzw. es keine Verbesserung gibt, dann lassen wir es so. Ich dachte, da diese Abfrage mehrmals im Code vorkommt, dass man sie auslagern könnte. 

Ok, `\printtext[parens]{\printnames[name:initials]{labelname}}` bleibt auch so drin. lieber den Code übersichtlich halten.

Damit sind wir auch schon beim nächsten Punkt. Die unterschiedlichen Einrücken liegen an den verschiedenen Programmen (TeXWorks, TeXMaker, TeXStudio), die ich benutze. Ich werde es auf zwei Leerzeichen ändern. 

bzgl. `\printnames[author][-\value{listtotal}]{editor}` muss ich noch schauen, aber mir scheint, dass `[-\value{listtotal}]` nicht notwendig ist, denn es sollen einfach alle Herausgeber genannt werden.

**Comment by moewew** [comment]
Theoretisch kann man `\ifboolexpr`-Abfragen in eigene Abfragen auslagern, aber da würde ich nur einen Sinn drin sehen, wenn die Abfrage sehr häufig vorkommt und eine eigene "Bedeutung" hat.

**Comment by LukasCBossert** [comment]
Ok, aber das sieht wesentlich komplexer aus. dann lassen wir es lieber doch bei der aktuellen Form und es erscheint dreimal im Code.
