### ISSUE TITLE
Abstand zwischen Autor/Titel und \bibstring{reviewof}

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#96]
V.a. im Blocksatz kommt ein längerer Abstand zwischen Autor und dem `\bibstring{reviewof}`, den ich mir nicht erklären kann.

<img width="792" alt="bildschirmfoto 2016-07-27 um 08 22 52" src="https://cloud.githubusercontent.com/assets/12896078/17165831/80f5cb0e-53d3-11e6-9289-f5a7de6f0c29.png">

```
%-----------------------
\DeclareBibliographyDriver{review}{%
 \usebibmacro{bibindex}%
 \usebibmacro{begentry}%
 \usebibmacro{author/editor}%
 \setunit*{\labelnamepunct}%
 \newblock%
 \iffieldundef{title}%
 {}%
 {\usebibmacro{title}}%
 \newunit\newblock%
 \usebibmacro{related:init}%
 \usebibmacro{related}% 
 \newunit\newblock%
 \usebibmacro{journal+number+year}%
 \newunit\newblock%
 \usebibmacro{pages}%
 \newunit\newblock%
 \usebibmacro{doi+eprint+url}%
 \usebibmacro{signatur}%
 \newunit\newblock%
 \usebibmacro{savestuff}%
 \usebibmacro{finentry}%
}
```
<img width="728" alt="bildschirmfoto 2016-07-27 um 08 26 30" src="https://cloud.githubusercontent.com/assets/12896078/17165884/dc19a50a-53d3-11e6-8821-ec5a3aee0782.png">

**Comment by moewew** [comment]
Mhh mit
```
\documentclass[a4paper,ngerman]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[style=archaeologie,initials=true]{biblatex}
\usepackage{hyperref}

\addbibresource{archaeologie-bibancient.bib}
\addbibresource{archaeologie-bibcorpora.bib}
\addbibresource{archaeologie-lstabbrv.bib}
\addbibresource{archaeologie-lstlocations.bib}
\addbibresource{archaeologie-lstpublishers.bib}
\addbibresource{archaeologie.bib}

\nocite{Bell2011,Hufschmid2010,Taylor2008}

\begin{document}
\printbibliography
\end{document}
```
sehe ich keine Probleme. Kannst Du Dein Bild in Code umwandeln?

**Comment by LukasCBossert** [comment]
Es hat echt eine Weile gedauert, bis ich ein MWE hatte, dass das Problem aufzeigt:

```
\documentclass[a4paper,ngerman]{scrbook}

\usepackage{babel}
\usepackage[				
backend=biber,
style=archaeologie,
	lstabbrv,
	lstlocations,
	lstpublishers,
	inreferences,
	initials,
	citeauthorformat=firstfull,
	bibfullname,
	publisher,
	scshape,
	width=9em,
	]{biblatex}
%%-------------------------

\usepackage{pgfplots}

\addto\extrasngerman{%
					\pgfplotsset{/pgf/number format/set decimal separator={,}}
					\pgfplotsset{/pgf/number format/set thousands separator = {.}}
					} 


\addbibresource{archaeologie.bib}

\nocite{Bell2011,Hufschmid2010,Taylor2008}

\begin{document}
	\printbibliography

\end{document}
```

Dabei habe ich auch gleich gesehen, woran es liegt: Es fehlen die `%`.
Es kommt zu keinem extra Abstand wenn man schreibt:
```
\addto\extrasngerman{%
					\pgfplotsset{/pgf/number format/set decimal separator={,}}%<----
					\pgfplotsset{/pgf/number format/set thousands separator = {.}}%<----
					} 
```

Wobei mir unerklärlich ist, wie diese `%` Auswirkungen auf den `\bibstring` haben.

**Comment by LukasCBossert** [comment]
Für mein Hauptdokument war dies nicht die Lösung des Problems, wohl aber für das MWE.

**Comment by moewew** [comment]
Hast Du noch mehr `\extrasngerman` (oder etwas ähnliches) in Deinem Hauptdokument? Es kann sein, dass in dem `related`-Code die Sprache umgestellt wird. Wenn in dem Sprachcode ungewollte Leerzeichen eingeführt wurden, dann zeigen sie sich hier jetzt.

**Comment by LukasCBossert** [comment]
In der Tat, so war es. Habe jetzt immer nach den `\extrasngerman`etc ein `%` und dabei wohl auch das richtige getroffen: Die Lücke ist geschlossen.
