### ISSUE TITLE
Umstellung der Jahresangabe

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/biblatex-archaeologie#98]
Mit `biblatex 3.5` wird das Feld `year` nicht mehr ausgelesen.

**Comment by LukasCBossert** [comment]
https://github.com/plk/biblatex-apa/issues/27 wird wohl mit version `3.6` behoben.

**Comment by moewew** [comment]
Nicht ganz, du musst in `\DeclareLabeldate` immer noch manuell `\field{year}` am besten nach `\field{date}` einfügen.
Der Default in `biblatex.def` ist
```
\DeclareLabeldate{%
  \field{date}
  \field{year}
  \field{eventdate}
  \field{origdate}
  \field{urldate}
  \literal{nodate}
}
```

Die jetzige Definition in `archaeologie.bbx` ist
```
\DeclareLabeldate{%
  \field{date}
  \field{eventdate}
  \field{origdate}
  \field{urldate}
  \field{pubstate}
  \literal{nodate}
}
```

und sollte dann wohl ein etwa
```
\DeclareLabeldate{%
  \field{date}
  \field{year}
  \field{eventdate}
  \field{origdate}
  \field{urldate}
  \field{pubstate}
  \literal{nodate}
}
```
lauten.

**Comment by LukasCBossert** [comment]
Danke. ist eingefügt.
Aber mir ist dann noch nicht klar, wie ich es hinbekomme, dass bspw. bei diesem Eintrag:
```
@Book{CIL,
  title     = CIL,
  location  = Berlin,
  shorthand = CIL-short,
  keywords  = {corpus},
  options   = {corpus},
  date      = {1863/open},
  owner     = {Lukas C. Bossert},
  timestamp = {2015-05-06},
}
```
bei `date={1863/open}` dann `1863--` hinbekomme. Das ist doch jetzt eine neue Funktion?! Es wird immer nur das Jahr genommen. Gleiches gilt auch bei Einträgen (die kein `year` haben) mit `date={1978/1988}`: Es sollte eigentlich `1978--1988` erscheinen, aber es wird nur `1978` ausgegeben. 
Diese Angabe ist ja für `year` nicht möglich?!

**Comment by moewew** [comment]
Mit diesen neuen EDTF-Datums-Features habe ich mich noch nicht richtig beschäftigt. Es gibt einige sehr lange Diskussionen im `biblatex` bugtracker, wo die Funktionen entwickelt und erklärt werden https://github.com/plk/biblatex/issues/461, https://github.com/plk/biblatex/issues/448, https://github.com/plk/biblatex/issues/447, https://github.com/plk/biblatex/issues/445, https://github.com/plk/biblatex/issues/427, https://github.com/plk/biblatex/issues/422. Auch im Changelog gibt es einiges dazu zu lesen (beachte auch die Hinweise zu nicht abwärtskompatiblen Änderungen, es *könnte* sein, dass Dich das auch betrifft) https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org. Tatsache ist, dass der Code in `authoryear.cbx` beispielsweise nun wesentlich länger geworden ist (besonders `cite:labelyear+extrayear`) https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/cbx/authoryear.cbx. Da muss Dein `cite:labelyear+extrayear` wohl mit der Zeit gehen.

**Comment by LukasCBossert** [comment]
hm, muss mal schauen, ob es dann reicht, wenn ich die Original-Defintion von `authoryear.cbx` einbaue.

**Comment by moewew** [comment]
Ich sehe gerade, dass ich einige Warnungen bekomme.

Zum einen `Package biblatex Warning: '\name' is deprecated in sorting specifications, please use '\field'.` Das kommt wohl von `\DeclareSortingScheme{nyt}`, wo es jetzt nur noch `\field` heißen sollte, nicht mehr `\name`.

Zum anderen
```
Package biblatex Warning: 'labeldate' option used to determine whether to provide label date fields and extrayear field is renamed to 'labeldateparts', setting this instead. This option is now used to set the format of the labeldate.
```
mehr dazu ist im oben verlinkten Changelog zu lesen.

**Comment by LukasCBossert** [comment]
Die `\DeclareSortingScheme` habe ich aus der `.bbx` ganz entfernt, da scheint mir der Unterschied zu der aus `standard.bbx` nicht gravierend zu sein (und die ist wahrscheinlich auch besser).

Ansonsten hoffe ich mal, dass alles wieder passt: zumindest kommt keine Fehlermeldung mehr.

**Comment by moewew** [comment]
Gut, der Unterschied in den Sortierschemata war schon da, Du hattest in Deiner Version noch `shorthand` in der Rangfolge vor den Namen. Wie sinnvoll das ist, wage ich nicht zu beurteilen. Allerdings nutzt Du `shorthands` recht exzessiv bei antiken Werken, da *könnte* das wieder relevant werden.

Mit der Änderung https://github.com/LukasCBossert/biblatex-archaeologie/commit/0acfa541baa05501461d2b7de9097db6e9328670#diff-5491ebad83f37b610fe1e99403aefd4fL244 hast Du wahrscheinlich einen Teil der `yearinparens`-Option ausgehebelt. Die war dafür da, zu bestimmen, in welchem Format das Jahr ausgegeben wird (Klammern oder nicht, denke ich) und benutzt das Feld-Format `citeyear`.

**Comment by LukasCBossert** [comment]
ah, stimmt. Die `shorthand`-Beispiele, die ich zum Testen genutzt habe, waren nicht ausreichend. habe also das ergänzt und eingebaut.

Die `yearinparens`-Option sollte wieder laufen, da ich die Änderung rückgängig gemacht habe. 
Ich schaffe es nicht, dass das Jahr mit der neuen Funktion `\open` etc. angezeigt wird. 

```
@Article{DeVisscher_1951-1952,
  author       = {de Visscher, Fernand and Mertens, Joseph},
  title        = {Les puits du Forum d'Alba Fucense},
  journaltitle = BCom,
  shortjournal = BCom-short,
  volume       = {74},
  pages        = {3--13},
  date         = {1951/1952},
}
```

sollte ja eigentlich `1951--1952` als `labeldate` verwenden, aber es wird nur `1951` ausgegeben.

**Comment by moewew** [comment]
Wenn Du das Makro `cite:labelyear+extrayear` nicht verwendest, dann musst Du seine Funktionen selbst nachbauen. Soweit ich weiß ist `\printfield{labelyear}\printfield{extrayear}` nicht (mehr?) ausreichend für Datums-Bereiche mit `endyear` und Krams. 

Warum schreibst Du nicht
```
\printtext[citeyear]{\usebibmacro{cite:labelyear+extrayear}}
```
Dann sollte doch alles im Lot sein.

**Comment by LukasCBossert** [comment]
Ich kann 
```
\newbibmacro*{cite:year}{%  
  \iffieldundef{labelyear}%
  {}%
  {\printtext[citeyear]{\usebibmacro{cite:labelyear+extrayear}}}%
  }```
schreiben, dann bekomme ich für `DeVisscher_1951-1952` `1951--1952` für das `labeldate`. 
Allerdings kann ich dann nicht analog 
```
\newbibmacro{journal+number+year}{%
 \usebibmacro{journal}%
 \setunit{\jourvoldelim}%
 \printfield{volume}%
 {\setunit{\volnumdelim}%
 \printfield{number}%
 }% 
 \newunit%
 \iffieldundef{year}%
 {\printfield{pubstate}}%
{\printtext{\usebibmacro{cite:labelyear+extrayear}}}%
}
```
schreiben (obwohl es für den vorliegenden Fall mit `DeVisscher_1951-1952` das richtige Ergebnis erzielt), weil das für `book` `incollection` etc hieße, dass die Jahreszahl am Ende auch ein `a` `b` etc. bekämen. 
Diese ›Erweiterung‹ ist ja nur für das Label notwendig, nicht mehr für den Bibliographieeintrag an sich. 
```
\newbibmacro*{location+edition+year}{%
  \ifboolexpr{%
    test {\iflistundef{location}}%
    and test {\iflistundef{publisher}}%
    and test {\iffieldundef{year}}}%
   {}%
   {\ifbool{bbx:publisher}%
     {\printtext[parens]{%
       \printlist{location}%
       \setunit*{\addcolon\addspace}%
       \printlist{publisher}%
       \iffieldint{edition}%
         {\setunit{\addspace}}%
         {\newunit}%
      \usebibmacro{edition}% 
      \iffieldundef{year}%
        {\printfield{pubstate}}%
        {\printtext{\usebibmacro{cite:labelyear+extrayear}}}%<<<<<Verändert! zuvor \printfield{year}
     \setunit*{\addspace}%
     \ifboolexpr{%
     test {\iflistundef{origlocation}}%
     and test {\iflistundef{origpublisher}}%
     and test {\iffieldundef{origyear}}}%
    {}%
    {\printtext[parens]{%
    \printlist{origlocation}%
    \iflistundef{origpublisher}%
      {}%
      {\setunit*{\addcolon\addspace}%
      \printlist{origpublisher}%
      }%
     \setunit{\addspace}%
     \printfield{origyear}%
      }% 
     }%
    }%
   }%
  {\usebibmacro{edition}%
   \printtext[parens]{%
   \ifboolexpr{%
     test {\iflistundef{origlocation}}%
     and test {\iffieldundef{origyear}}%
     }%
   {}%
   {\iflistundef{origlocation}%
   {\printlist{location}}%
   {\printlist{origlocation}}% 
   \setunit{\addspace}%
   \printfield{origyear}%
   \setunit*{\addsemicolon\addspace}%
   \iffieldundef{origyear}%
   {}%
   {\bibstring{reprint}%
    \addspace%
   }%
  }%
  \printlist{location}%
  \setunit*{\addspace}%
  \iffieldundef{year}%
  {\printfield{pubstate}}%
  {\printfield{year}}% 
  }%
  }%
 }%
}
```

**Comment by LukasCBossert** [comment]
aha. ich habe in der `standard.bbx` geschaut: `\usebibmacro{date}` macht das, was es soll.

**Comment by LukasCBossert** [comment]
So, alles scheint zu funktionieren, nur die Angabe bei `pubstate` wird im `labeldate` nicht entsprechend der Sprache ausgegeben:
```
@Article{Flecker_inpress,
  author       = {Flecker, Manuel and Lipps, Johannes and Broisch, Manuela},
  title        = {Geophysikalische Untersuchungen im sog. \emph{comitium} am Forum von Pompeji},
  journaltitle = {Kölner und Bonner Archaeologica},
  shortjournal = {KuBA},
  pubstate     = {inpress},
  file         = {:Artikel_Monographien/Flecker, Lipps and Broisch_(Flecker_inpress)_Geophysikalische Untersuchungen im sog. _emphcomitium am Forum von Pompeji.pdf:PDF},
  groups       = {S636 Pompeii},
  owner        = {Lukas C. Bossert},
  timestamp    = {2016-04-26},
}
```
heißt `Flecker u.a. inpress` aber im Bibliographieeintrag `im Druck
![bildschirmfoto 2016-09-19 um 00 59 48](https://cloud.githubusercontent.com/assets/12896078/18619728/65e2c352-7e04-11e6-90e8-2d77a72b67c3.png)
`.

**Comment by moewew** [comment]
War es denn früher anders? Was hier passiert ist, dass einfach der Inhalt des Felds `pubstate` in `labelyear` kopiert wird (grob zumindest - inzwischen ist das alles viel komplizierter, aber ich glaube als Analogie funktioniert es noch). Das wird dann ausgegeben, es wird vorher kein `\bibstring` drübergejagt. Wenn Du hingegen das Feld `pubstate` druckst, dann wird da halt `\bibstring` angewendet und Du bekommst "im Druck".

**Comment by moewew** [comment]
... Kaum hatte ich das gesprochen, lag ein Update zu `biblatex` 3.6 vor der Tür, das ein bisschen in der Expandierung der Argumente herumfummelt, und siehe da, bei mir bekomme ich jetzt überall "im Druck".

**Comment by LukasCBossert** [comment]
hast du das auch mit der `cbx` aus dem Repo hier probiert? Ich habe auch biblatex `3.6` drauf, aber weiterhin `inpress` und erst dann `im Druck`.

**Comment by LukasCBossert** [comment]
Mit 
```
\newbibmacro*{cite:year}{%  
  \iffieldundef{labelyear}%
  {}%
  {{\printtext[citeyear]{\printfield{labelyear}\printfield{extrayear}}}}%
  }
```
bekomme ich `im Druck`;
mit 
```
\newbibmacro*{cite:year}{%  
  \iffieldundef{labelyear}%
  {}%
  {\printtext[citeyear]{\usebibmacro{cite:labelyear+extrayear}}}%
  }
```
kommt wieder `inpress`.

**Comment by moewew** [comment]
Ach je, ja ich sehe es. Ich weiß nicht genau, welche Version der `.bbx`/`.cbx` ich vorher hatte.
Probier es mal mit
```
\renewbibmacro*{cite:labelyear+extrayear}{%
  \iffieldundef{labelyear}
    {}
    {\printtext[bibhyperref]{%
     \ifdefstring\blx@dateformat@labeldate{edtf}
       {}
       {\datecircaprint}%
     \dateeraprintpre{labelyear}%
     \iffieldnums{labelyear}
       {\mkyearzeros{\thefield{labelyear}}}
       {\printfield{labelyear}}%
     \printfield{extrayear}%
     \iffieldsequal{labeldateera}{labelenddateera}{}
       {\dateeraprint{labelyear}}%
     \dateuncertainprint%
     \ifdefstring\blx@dateformat@labeldate{edtf}
       {\datecircaprintedtf}
       {}%
     \iffieldundef{labelendyear}
       {}
       {\iffieldsequal{labelyear}{labelendyear}{}
        {\ifdefstring\blx@dateformat@labeldate{edtf}
          {\slash}% strict EDTF
          {\bibdaterangesep
           \enddatecircaprint}%
         \dateeraprintpre{labelendyear}%
         \mkyearzeros{\thefield{labelendyear}}%
         \enddateuncertainprint
         \ifdefstring\blx@dateformat@labeldate{edtf}
           {\enddatecircaprintedtf}
           {}%
         \dateeraprint{labelendyear}}}}}}
```
Da ist die Abfrage `\iffieldnums{labelyear}` neu. (Diese EDTF-Datums-Features werden mir immer unsympathischer.)

**Comment by moewew** [comment]
Ich habe dazu nochmal offiziell nachgefragt https://github.com/plk/biblatex/issues/478

**Comment by LukasCBossert** [comment]
Mit deinem `\renewbibmacro*{cite:labelyear+extrayear}{...}` funktioniert es. wobei es reicht `newbibmacro` zu machen, da es ja in der `authoryear.cbx` definiert wird und nicht in der `standard.cbx` --> Ein Mängel unseres Stils, den wir lieber auf `authoryear` anstatt auf `standard` aufbauen hätten sollen. 

Ich bin gespannt was bei deinem Issue #478 rauskommt. Ist demnach wohl ein bug?!

**Comment by moewew** [comment]
Achso, ja, wenn das Makro vorher nicht da war, ist `\newbibmacro` natürlich die bessere Wahl.

Ob das ein Bug ist oder nicht, wage ich nicht zu beurteilen. Dieses neue EDTF-Gewurschtle hat den Code für die Jahresausgabe halt gehörig verkompliziert und aufgeblasen. Ich habe den Verdacht, dass nicht alle Teile des Code mitgezogen haben (und die deshalb noch wie früher funktionieren). Als die Sache implementiert wurde, hatte ich gehofft, man würde das, was jetzt im Makro `cite:labelyear+extrayear` irgendwie so lösen können, dass es unter der Haube passiert und nicht von einem Stil-Autor repliziert werden muss.

**Comment by LukasCBossert** [comment]
Mit den EDTF-Sachen komme ich nicht klar, ich bin froh, wenn ich halbwegs nachvollziehen kann, was im Code passiert.

Ich finde es etwas ungewöhnlich, dass ich bei 
```
@Article{DeVisscher_1951-1952,
  author       = {de Visscher, Fernand and Mertens, Joseph},
  title        = {Les puits du Forum d'Alba Fucense},
  journaltitle = BCom,
  shortjournal = BCom-short,
  volume       = {74},
  pages        = {3--13},
  year         = {1951--1952},
}
```
eine Fehlermeldung nach dem `biber`-Durchlauf bekomme, weil `year` nicht richtig angegeben ist, (`WARN - year field '1951--1952' in entry 'DeVisscher_1951-1952' is not an integer - this will probably not sort properly.`). 
Es scheint mir aber ungewöhnlich in solchen Fällen auf `date` umsteigen zu müssen (auch wenn die Ausgabe gleich aussieht, so möchte man doch Fehlermeldungen vermeiden).

**Comment by moewew** [comment]
Ja, du solltest `date` nutzen, denn nur das Feld wird volständig geparst, soweit ich das weiß. Bei `year` wird nur überprüft, ob es eine ganze Zahl ist, die man sortieren kann. Datumsbereiche werden übrigens *nicht* mit `--` getrennt, sondern mit `/`. Korrekt ist also

```
@Article{DeVisscher_1951-1952,
  author       = {de Visscher, Fernand and Mertens, Joseph},
  title        = {Les puits du Forum d'Alba Fucense},
  journaltitle = BCom,
  shortjournal = BCom-short,
  volume       = {74},
  pages        = {3--13},
  date         = {1951/1952},
}
```
Generell ist es eine gute Idee von `date` auf `year` umzusteigen. Einzig, wenn Du wirklich nur eine Jahreszahl hast, sind beide Versionen gleich gut.

**Comment by LukasCBossert** [comment]
ok, dann werde ich bei allen Angaben, die nicht nur die Jahreszahl enthalten, darauf hinweisen, dass `date` verwendet wird. 

Wird sich deiner Einschätzung aufgrund deines issues #478 etwas am Code ändern, sodass man mit einem upload auf CTAN noch warten soll?

**Comment by moewew** [comment]
Keine Ahnung. Wenn Du noch etwas Zeit hast, dann warte vielleicht noch ein bisschen. Es kann aber auch sein, dass der Bugreport erstmal ein bisschen liegen bleibt, weil es Wichtigeres gibt. Insbesondere denke ich aber nicht, dass deswegen noch schnell ein Update hinterhergeschoben wird.

Ansonsten kannst Du natürlich jetzt die funktionierende Version losschicken, ich halte es für unwahrscheinlich, dass in ganz naher Zukunft eine neue `biblatex`-Version rauskommt, die das zerstört. Wenn wegen https://github.com/plk/biblatex/issues/478 irgendetwas geändert wird, hast du wahrscheinlich immer noch genug Zeit, dich darauf vorzubereiten.

**Comment by LukasCBossert** [comment]
Gut, dann mach ich ein Update von `archaeologie` fertig, dann können alle mit biblatex `3.6` den Stil wieder nutzen. Vielen Dank für deine Hilfe.
